# Generated by Django 5.2.6 on 2026-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoice_paid_at_invoicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='business_address',
            field=models.TextField(blank=True, default='', help_text='Vendor business address'),
        ),
        migrations.AddField(
            model_name='expense',
            name='item_description',
            field=models.CharField(blank=True, default='', help_text='Item or service description', max_length=300),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_photo',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/receipts/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='low_stock_alert_level',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Alert when stock falls to or below this level', max_digits=15),
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='supplier_brand',
            field=models.CharField(blank=True, default='', help_text='Supplier or brand name', max_length=200),
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='units_per_piece',
            field=models.DecimalField(decimal_places=4, default=1, help_text='How many units per piece/pack', max_digits=15),
        ),
        migrations.AddField(
            model_name='supplymovement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20),
        ),
    ]
