# Generated by Django 5.2.6 on 2026-03-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expense_business_address_expense_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplymovement',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='supplymovement',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Document reference (e.g. IST-000001)', max_length=100),
        ),
    ]
