# Generated by Django 5.2.6 on 2026-03-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_grand_total_cogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date the invoice was fully paid (used for financial reporting date filter).', null=True),
        ),
    ]
