# Generated by Django 5.2.6 on 2026-05-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_delivery_charge_to_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyitem',
            options={'ordering': ['-created_at']},
        ),
    ]
