# Generated by Django 5.2.6 on 2026-03-07 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_item_item_type'),
        ('partners', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPriceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(help_text='Descriptive name, e.g. "VIP Wholesale Pricing".', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_catalogs', to='partners.customer')),
            ],
            options={
                'ordering': ['customer__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPriceCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.customerpricecatalog')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_prices', to='catalog.item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit')),
            ],
            options={
                'ordering': ['item__code'],
                'unique_together': {('catalog', 'item', 'unit')},
            },
        ),
    ]
