# Generated by Django 5.2.6 on 2026-05-14 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], max_length=10)),
                ('db_table', models.CharField(db_index=True, max_length=100)),
                ('app_label', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('row_pk', models.IntegerField()),
                ('row_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sync_syncou_status_0bc0ca_idx')],
            },
        ),
    ]
