# Generated by Django 5.2.6 on 2026-05-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_neonchangelog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='neonchangelog',
            new_name='sync_neonch_db_tabl_773f80_idx',
            old_name='sync_neoncha_db_tabl_idx',
        ),
        migrations.RenameIndex(
            model_name='neonchangelog',
            new_name='sync_neonch_created_03a322_idx',
            old_name='sync_neoncha_created_idx',
        ),
    ]
