# Generated by Django 6.0.2 on 2026-03-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_fee_discount_other_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy manual override — use service_fee instead.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='serviceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Selling price per unit (auto-filled from Item catalog)', max_digits=15),
        ),
    ]
