# Generated by Django 5.2.6 on 2026-03-25 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_customerpricecatalog_effective_dates'),
        ('services', '0003_alter_customerservice_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservice',
            name='service_fee',
        ),
        migrations.AddField(
            model_name='customerservice',
            name='bundle',
            field=models.ForeignKey(blank=True, help_text='Optional price-list bundle applied to this service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bundles', to='pricing.pricelist'),
        ),
        migrations.AddField(
            model_name='customerservice',
            name='quotation',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Total amount quoted to the customer for this service.', max_digits=15, null=True),
        ),
    ]
