# Generated by Django 5.2.6 on 2026-03-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_customerpricecatalog_effective_dates'),
        ('services', '0004_quotation_and_bundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservice',
            name='bundle',
        ),
        migrations.CreateModel(
            name='ServiceBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_multiplier', models.DecimalField(decimal_places=4, default=1, help_text='Multiply every PriceListItem qty by this factor (usually 1).', max_digits=15)),
                ('discount_type', models.CharField(choices=[('FIXED', 'Fixed Amount (₱)'), ('PERCENT', 'Percentage (%)')], default='PERCENT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=4, default=0, help_text='Bundle-level discount value.', max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_bundle_lines', to='pricing.pricelist')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='services.customerservice')),
            ],
        ),
    ]
