# Generated by Django 5.2.6 on 2026-03-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_bundle_formset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebundle',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='servicebundle',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='servicebundle',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='servicebundle',
            name='qty_multiplier',
        ),
    ]
