# Generated by Django 5.2.6 on 2026-03-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_simplify_service_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebundle',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Number of full bundle sets.', max_digits=10),
        ),
    ]
