# Generated by Django 5.2.6 on 2026-03-25 16:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_add_qty_to_service_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='partial_payment_amount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal('0'),
                help_text='Amount already paid by the customer when payment status is Partially Paid.',
                max_digits=15,
                null=True,
            ),
        ),
    ]
