# Generated by Django 6.0.2 on 2026-04-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_add_unit_cost_to_other_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceothermaterial',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cost paid to vendor per unit (for COGS calculation)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='serviceothermaterial',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Price charged to customer per unit', max_digits=15),
        ),
    ]
