# Generated by Django 6.0.2 on 2026-04-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_serviceothermaterial_unit_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid by customer when creating the service (for partial or full payment).', max_digits=15, null=True),
        ),
    ]
