# Generated by Django 5.2.6 on 2026-03-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowtransaction',
            name='is_auto_generated',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this entry was created automatically by a system signal'),
        ),
        migrations.AddField(
            model_name='cashflowtransaction',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='PK of the originating document', null=True),
        ),
        migrations.AddField(
            model_name='cashflowtransaction',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Model class name of the originating document (e.g. GoodsReceipt, POSSale)', max_length=50),
        ),
        migrations.AlterField(
            model_name='cashflowtransaction',
            name='category',
            field=models.CharField(choices=[('PROCUREMENT', 'Procurement'), ('SALES', 'Sales'), ('SUPPLIES', 'Supplies'), ('EXPENSES', 'Expenses'), ('CAPITAL', 'Capital'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
    ]
