# Generated by Django 6.0.2 on 2026-04-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0004_add_opening_closing_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycashflowsummary',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net profit (capital - expenses) - DEPRECATED, use net_cash_flow', max_digits=15),
        ),
    ]
