# Generated by Django 5.2.6 on 2026-04-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0007_add_cash_flow_and_pl_separation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycashflowsummary',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Assets: Cash + Inventory + AR at end of month', max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlycashflowsummary',
            name='expenses_procurement',
            field=models.DecimalField(decimal_places=2, default=0, help_text='⚠️ DEPRECATED for P&L - Use cogs_actual instead. Procurement is asset conversion (Cash→Inventory), not an expense. Keep for cash flow tracking only.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlycashflowsummary',
            name='expenses_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total expenses (COGS + operational + other) - excludes procurement', max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlycashflowsummary',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Assets: Cash + Inventory + AR at start of month', max_digits=15),
        ),
    ]
