# Generated by Django 5.2.6 on 2026-04-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0008_alter_monthlycashflowsummary_closing_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycashflowsummary',
            name='ar_collections',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual AR collections (invoice payments) this month', max_digits=15),
        ),
    ]
