# Generated by Django 5.2.6 on 2026-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0009_add_ar_collections_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycashflowsummary',
            name='expenses_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total operating expenses (operational + supplies + other) — excludes COGS and procurement', max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlycashflowsummary',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net profit: Gross Profit (Revenue - COGS) minus Operating Expenses', max_digits=15),
        ),
    ]
