# Generated by Django 5.2.6 on 2026-07-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0010_alter_monthlycashflowsummary_expenses_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycashflowsummary',
            name='collection_rate_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of invoices collected. Can exceed 100% when a month collects on prior-month AR against little new revenue.', max_digits=9),
        ),
        migrations.AlterField(
            model_name='monthlycashflowsummary',
            name='gross_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gross profit margin percentage', max_digits=9),
        ),
    ]
