from django.core.paginator import Paginator
from django.db.models import ProtectedError, Q


def sort_queryset(request, queryset, sort_map, default_key, default_dir='desc'):
    """
    Apply server-side ordering to `queryset` based on `?sort=`/`?dir=` query params.

    sort_map: dict mapping a public sort key (used in the URL) to a real model
    field name, or a list of field names for multi-field ordering (e.g.
    {'date': ['date', 'created_at']}). Falls back to `default_key`/`default_dir`
    when no/invalid sort param is given, so tables default to latest-first.

    Returns (ordered_queryset, resolved_sort_key, resolved_dir).
    """
    sort_key = request.GET.get('sort') or default_key
    if sort_key not in sort_map and sort_key != default_key:
        sort_key = default_key
    direction = request.GET.get('dir') or (default_dir if sort_key == default_key else 'asc')
    if direction not in ('asc', 'desc'):
        direction = 'asc'

    # default_key may be a fallback ordering that isn't exposed as a clickable
    # column (e.g. 'created_at' used only to make the default "latest first")
    fields = sort_map.get(sort_key, sort_key)
    if isinstance(fields, str):
        fields = [fields]
    if direction == 'desc':
        fields = [f if f.startswith('-') else f'-{f}' for f in fields]
    else:
        fields = [f[1:] if f.startswith('-') else f for f in fields]

    return queryset.order_by(*fields), sort_key, direction


PER_PAGE_CHOICES = ('10', '25', '50', '100', 'all')


def search_queryset(request, queryset, fields, param='q'):
    """
    Apply a case-insensitive OR search across `fields` (model field lookups,
    e.g. 'code', 'name', 'customer__name') using the `?q=` query param.

    Returns the queryset unchanged when no search term is present.
    """
    term = request.GET.get(param, '').strip()
    if not term:
        return queryset
    query = Q()
    for field in fields:
        query |= Q(**{f'{field}__icontains': term})
    return queryset.filter(query).distinct()


def paginate_queryset(request, queryset, per_page=25, param='page', per_page_param='per_page'):
    """
    Thin wrapper around Django's Paginator; returns a Page object.

    Reads `per_page` from the querystring (10/25/50/100/'all') so list views
    can expose a "Show entries" control without changing call sites — the
    resolved page size is available to templates via `page_obj.paginator.per_page`.
    """
    raw = request.GET.get(per_page_param, '')
    if raw == 'all':
        count = queryset.count()
        per_page = count or 1
    elif raw.isdigit() and int(raw) > 0:
        per_page = int(raw)
    paginator = Paginator(queryset, per_page)
    return paginator.get_page(request.GET.get(param, 1))


def build_relation_summary(obj):
    """
    Return a simple relation name list (without fetching objects) for display in delete warnings.
    Example: "Relations: orders, items, invoices" or "Relations: none detected."
    """
    relation_names = []
    for rel in obj._meta.get_fields():
        if not getattr(rel, 'auto_created', False) or getattr(rel, 'concrete', False):
            continue
        accessor = rel.get_accessor_name()
        # Skip reverse OneToOne autogenerated names without accessor
        if not accessor:
            continue
        verbose = getattr(getattr(rel, 'related_model', None), '_meta', None)
        verbose_name = getattr(verbose, 'verbose_name', accessor)
        relation_names.append(str(verbose_name))
    if relation_names:
        return 'Relations: ' + ', '.join(sorted(set(relation_names)))
    return 'Relations: none detected.'


def format_in_use_message(base_msg, relation_summary=None):
    msg = base_msg
    if relation_summary:
        msg = f"{msg} Details: {relation_summary}"
    return msg


def handle_delete_error(request, base_msg, relation_summary=None):
    msg = format_in_use_message(base_msg, relation_summary)
    if getattr(request, '_is_modal', False):
        from django.http import JsonResponse
        return JsonResponse({'success': False, 'message': msg})
    from django.contrib import messages
    messages.error(request, msg)
    return None


def handle_delete_success(request, success_msg):
    if getattr(request, '_is_modal', False):
        from django.http import JsonResponse
        return JsonResponse({'success': True, 'message': success_msg})
    from django.contrib import messages
    messages.success(request, success_msg)
    return None


def handle_protected_error(request, exc, base_msg, fallback_relation_summary=None):
    relation_summary = fallback_relation_summary
    if not relation_summary and hasattr(exc, 'protected_objects'):
        objs = list(exc.protected_objects[:5])
        if objs:
            names = []
            for o in objs:
                model_label = getattr(getattr(o, '_meta', None), 'verbose_name', o.__class__.__name__)
                names.append(f"{model_label}: {o}")
            extra = ', '.join(names)
            if len(exc.protected_objects) > len(objs):
                extra += '…'
            relation_summary = f"Referenced by: {extra}"
    if not relation_summary:
        relation_summary = 'Referenced by other records (e.g., posted documents or transactions).'
    return handle_delete_error(request, base_msg, relation_summary)
