from django.db.models import ProtectedError


def build_relation_summary(obj):
    """
    Return a simple relation name list (without fetching objects) for display in delete warnings.
    Example: "Relations: orders, items, invoices" or "Relations: none detected."
    """
    relation_names = []
    for rel in obj._meta.get_fields():
        if not getattr(rel, 'auto_created', False) or getattr(rel, 'concrete', False):
            continue
        accessor = rel.get_accessor_name()
        # Skip reverse OneToOne autogenerated names without accessor
        if not accessor:
            continue
        verbose = getattr(getattr(rel, 'related_model', None), '_meta', None)
        verbose_name = getattr(verbose, 'verbose_name', accessor)
        relation_names.append(str(verbose_name))
    if relation_names:
        return 'Relations: ' + ', '.join(sorted(set(relation_names)))
    return 'Relations: none detected.'


def format_in_use_message(base_msg, relation_summary=None):
    msg = base_msg
    if relation_summary:
        msg = f"{msg} Details: {relation_summary}"
    return msg


def handle_delete_error(request, base_msg, relation_summary=None):
    msg = format_in_use_message(base_msg, relation_summary)
    if getattr(request, '_is_modal', False):
        from django.http import JsonResponse
        return JsonResponse({'success': False, 'message': msg})
    from django.contrib import messages
    messages.error(request, msg)
    return None


def handle_delete_success(request, success_msg):
    if getattr(request, '_is_modal', False):
        from django.http import JsonResponse
        return JsonResponse({'success': True, 'message': success_msg})
    from django.contrib import messages
    messages.success(request, success_msg)
    return None


def handle_protected_error(request, exc, base_msg, fallback_relation_summary=None):
    relation_summary = fallback_relation_summary
    if not relation_summary and hasattr(exc, 'protected_objects'):
        objs = list(exc.protected_objects[:5])
        if objs:
            names = []
            for o in objs:
                model_label = getattr(getattr(o, '_meta', None), 'verbose_name', o.__class__.__name__)
                names.append(f"{model_label}: {o}")
            extra = ', '.join(names)
            if len(exc.protected_objects) > len(objs):
                extra += '…'
            relation_summary = f"Referenced by: {extra}"
    if not relation_summary:
        relation_summary = 'Referenced by other records (e.g., posted documents or transactions).'
    return handle_delete_error(request, base_msg, relation_summary)
