from decimal import Decimal
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from django.utils import timezone

from services.models import CustomerService, ServiceLine, ServiceStatus
from services.forms import CustomerServiceForm, CustomerServiceEditForm, ServiceLineFormSet


# ═══════════════════════════════════════════════════════════════════════════
# SERVICE INVOICE LIST
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_invoice_list(request):
    """List all invoices generated by customer services (service-type only)."""
    from core.models import Invoice
    from django.db.models import Sum, Q
    from django.db.models.functions import Coalesce
    from django.db.models import DecimalField

    # Invoices that have at least one linked customer service
    invoice_ids = CustomerService.objects.filter(
        invoice__isnull=False
    ).values_list('invoice_id', flat=True).distinct()

    qs = Invoice.objects.filter(pk__in=invoice_ids).select_related(
        'created_by'
    ).prefetch_related('customer_services', 'payments').order_by('-date')

    # Optional filters
    paid_filter = request.GET.get('paid', '')
    if paid_filter == '1':
        qs = qs.filter(is_paid=True)
    elif paid_filter == '0':
        qs = qs.filter(is_paid=False)

    # Totals
    agg = qs.aggregate(
        total_revenue=Coalesce(Sum('grand_total'), Decimal('0'), output_field=DecimalField()),
    )

    return render(request, 'services/service_invoice_list.html', {
        'invoices': qs,
        'paid_filter': paid_filter,
        'total_revenue': agg['total_revenue'],
    })


# ═══════════════════════════════════════════════════════════════════════════
# LIST
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_list(request):
    status_filter = request.GET.get('status', '')
    qs = CustomerService.objects.select_related('created_by', 'invoice')
    if status_filter:
        qs = qs.filter(status=status_filter)
    return render(request, 'services/service_list.html', {
        'services': qs,
        'status_filter': status_filter,
        'statuses': ServiceStatus.choices,
    })


# ═══════════════════════════════════════════════════════════════════════════
# DETAIL
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_detail(request, pk):
    svc = get_object_or_404(
        CustomerService.objects.select_related('invoice', 'warehouse', 'created_by', 'posted_by')
        .prefetch_related('lines__item', 'lines__unit', 'lines__location'),
        pk=pk,
    )
    # ── P&L Calculations ─────────────────────────────────────────────────
    line_cogs = Decimal('0')
    line_pnl = []
    for line in svc.lines.all():
        cost = (line.item.cost_price or Decimal('0')) * line.qty
        line_pnl.append({
            'line': line,
            'cogs': cost,
            'profit': line.line_total - cost,
        })
        line_cogs += cost
    revenue = svc.grand_total or Decimal('0')
    gross_profit = revenue - line_cogs
    gross_margin = (gross_profit / revenue * 100) if revenue > 0 else Decimal('0')

    return render(request, 'services/service_detail.html', {
        'service': svc,
        'line_pnl': line_pnl,
        'service_cogs': line_cogs,
        'service_revenue': revenue,
        'gross_profit': gross_profit,
        'gross_margin': gross_margin,
    })


# ═══════════════════════════════════════════════════════════════════════════
# CREATE
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_create(request):
    if request.method == 'POST':
        form = CustomerServiceForm(request.POST)
        formset = ServiceLineFormSet(request.POST, prefix='lines')
        if form.is_valid():
            svc = form.save(commit=False)
            svc.created_by = request.user
            svc.save()
            formset = ServiceLineFormSet(request.POST, instance=svc, prefix='lines')
            if formset.is_valid():
                formset.save()
                messages.success(request, f'Service {svc.service_number} created.')
                return redirect('service_detail', pk=svc.pk)
    else:
        form = CustomerServiceForm()
        formset = ServiceLineFormSet(prefix='lines')
    return render(request, 'services/service_form.html', {
        'form': form,
        'formset': formset,
        'title': 'New Customer Service',
        'is_create': True,
    })


# ═══════════════════════════════════════════════════════════════════════════
# EDIT
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_edit(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if svc.status in (ServiceStatus.COMPLETED, ServiceStatus.CANCELLED):
        messages.error(request, 'Cannot edit a Completed or Cancelled service.')
        return redirect('service_detail', pk=pk)
    if request.method == 'POST':
        form = CustomerServiceEditForm(request.POST, instance=svc)
        formset = ServiceLineFormSet(request.POST, instance=svc, prefix='lines')
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            messages.success(request, f'Service {svc.service_number} updated.')
            return redirect('service_detail', pk=svc.pk)
    else:
        form = CustomerServiceEditForm(instance=svc)
        formset = ServiceLineFormSet(instance=svc, prefix='lines')
    return render(request, 'services/service_form.html', {
        'form': form,
        'formset': formset,
        'title': f'Edit Service: {svc.service_number}',
        'service': svc,
        'is_create': False,
    })


# ═══════════════════════════════════════════════════════════════════════════
# DELETE
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_delete(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if svc.status == ServiceStatus.COMPLETED:
        messages.error(request, 'Cannot delete a Completed service.')
        return redirect('service_detail', pk=pk)
    if request.method == 'POST':
        svc.delete()
        messages.success(request, 'Service deleted.')
        return redirect('service_list')
    return render(request, 'services/service_delete.html', {'service': svc})


# ═══════════════════════════════════════════════════════════════════════════
# MARK IN-PROGRESS
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_start(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if request.method == 'POST':
        if svc.status == ServiceStatus.DRAFT:
            svc.status = ServiceStatus.IN_PROGRESS
            svc.save(update_fields=['status', 'updated_at'])
            messages.success(request, f'Service {svc.service_number} marked as In Progress.')
        else:
            messages.error(request, 'Only DRAFT services can be started.')
    return redirect('service_detail', pk=pk)


# ═══════════════════════════════════════════════════════════════════════════
# COMPLETE — deducts inventory + generates invoice
# ═══════════════════════════════════════════════════════════════════════════
@login_required
@transaction.atomic
def service_complete(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if request.method != 'POST':
        return redirect('service_detail', pk=pk)

    if svc.status not in (ServiceStatus.DRAFT, ServiceStatus.IN_PROGRESS):
        messages.error(request, 'Only Draft or In Progress services can be completed.')
        return redirect('service_detail', pk=pk)

    now = timezone.now()
    lines = list(svc.lines.select_related(
        'item__default_unit', 'item__selling_unit', 'unit', 'location__warehouse'
    ).all())

    # ── Inventory deduction ────────────────────────────────────────────────
    if lines:
        try:
            from inventory.models import StockMove, StockBalance, MoveType, MoveStatus
            from catalog.models import convert_to_base_unit
            from warehouses.models import Location

            # Resolve default location for the service warehouse (used as fallback)
            default_location = None
            if svc.warehouse_id:
                default_location = (
                    Location.objects
                    .filter(warehouse=svc.warehouse, is_pickable=True)
                    .order_by('code')
                    .first()
                )

            missing_location_items = []
            moves = []
            for line in lines:
                location = line.location or default_location
                if location is None:
                    missing_location_items.append(line.item.code)
                    continue

                base_qty = convert_to_base_unit(
                    line.qty, line.unit, line.item.stock_unit, item=line.item
                )
                move = StockMove(
                    move_type=MoveType.SERVICE_OUT,
                    item=line.item,
                    qty=base_qty,
                    unit=line.item.stock_unit,
                    from_location=location,
                    to_location=None,
                    reference_type='CustomerService',
                    reference_id=svc.pk,
                    reference_number=svc.service_number,
                    batch_number='',
                    serial_number='',
                    status=MoveStatus.POSTED,
                    created_by=request.user,
                    posted_by=request.user,
                    posted_at=now,
                )
                moves.append(move)

                # Deduct stock balance (in stock_unit)
                balance, _ = StockBalance.objects.select_for_update().get_or_create(
                    item=line.item,
                    location=location,
                    defaults={'qty_on_hand': Decimal('0'), 'qty_reserved': Decimal('0')},
                )
                balance.qty_on_hand -= base_qty
                wh = location.warehouse
                if not wh.allow_negative_stock and balance.qty_on_hand < 0:
                    raise ValueError(
                        f"Insufficient stock for {line.item.code} at {location}. "
                        f"Available: {balance.qty_on_hand + base_qty}, Requested: {base_qty}"
                    )
                balance.save()

            if moves:
                StockMove.objects.bulk_create(moves)

            if missing_location_items:
                messages.warning(
                    request,
                    f'No location set for item(s): {", ".join(missing_location_items)}. '
                    'Their stock was NOT deducted. Set a location on service lines or assign a warehouse.'
                )

        except ValueError as exc:
            messages.error(request, f'Stock error: {exc}')
            return redirect('service_detail', pk=pk)

    # ── Generate Invoice ───────────────────────────────────────────────────
    from core.models import Invoice, InvoiceLine
    from core.views import _next_invoice_number

    grand_total = svc.grand_total or Decimal('0')

    inv = Invoice.objects.create(
        invoice_number=_next_invoice_number(),
        date=now.date(),
        customer_name=svc.customer_name,
        customer_address=svc.address,
        subtotal=grand_total,
        grand_total=grand_total,
        notes=f'Service: {svc.service_name}',
        created_by=request.user,
    )

    if lines:
        for line in lines:
            InvoiceLine.objects.create(
                invoice=inv,
                item_code=line.item.code,
                item_name=line.item.name,
                qty=line.qty,
                unit=line.unit.abbreviation,
                unit_price=line.unit_price,
                line_total=line.line_total,
            )
    else:
        # No lines — create single summary line
        InvoiceLine.objects.create(
            invoice=inv,
            item_code='SVC',
            item_name=svc.service_name,
            qty=Decimal('1'),
            unit='svc',
            unit_price=grand_total,
            line_total=grand_total,
        )

    # ── Mark service completed ─────────────────────────────────────────────
    svc.status = ServiceStatus.COMPLETED
    svc.invoice = inv
    svc.posted_by = request.user
    svc.posted_at = now
    if not svc.completion_date:
        svc.completion_date = now.date()
    svc.save(update_fields=[
        'status', 'invoice', 'posted_by', 'posted_at',
        'completion_date', 'updated_at',
    ])

    messages.success(
        request,
        f'Service {svc.service_number} completed. Invoice {inv.invoice_number} generated.'
    )
    return redirect('service_detail', pk=pk)


# ═══════════════════════════════════════════════════════════════════════════
# CANCEL
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_cancel(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if request.method == 'POST':
        if svc.status in (ServiceStatus.DRAFT, ServiceStatus.IN_PROGRESS):
            svc.status = ServiceStatus.CANCELLED
            svc.save(update_fields=['status', 'updated_at'])
            messages.success(request, f'Service {svc.service_number} cancelled.')
        else:
            messages.error(request, 'Cannot cancel a Completed service.')
    return redirect('service_detail', pk=pk)
