from decimal import Decimal
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from django.db.models import Prefetch
from django.utils import timezone

from services.models import CustomerService, ServiceLine, ServiceOtherMaterial, ServiceBundle, ServiceStatus, ServicePaymentStatus
from accounts.decorators import write_denied_for_viewer
from services.forms import (
    CustomerServiceForm, CustomerServiceEditForm,
    ServiceLineFormSet, ServiceOtherMaterialFormSet, ServiceBundleFormSet,
)


# ═══════════════════════════════════════════════════════════════════════════
# SERVICE INVOICE LIST
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_invoice_list(request):
    """List all invoices generated by customer services (service-type only)."""
    from core.models import Invoice
    from django.db.models import Sum, Q
    from django.db.models.functions import Coalesce
    from django.db.models import DecimalField

    # Invoices that have at least one linked customer service
    invoice_ids = CustomerService.objects.filter(
        invoice__isnull=False
    ).values_list('invoice_id', flat=True).distinct()

    qs = Invoice.objects.filter(pk__in=invoice_ids).select_related(
        'created_by'
    ).prefetch_related('customer_services', 'payments').order_by('-date')

    # Optional filters
    paid_filter = request.GET.get('paid', '')
    if paid_filter == '1':
        qs = qs.filter(is_paid=True)
    elif paid_filter == '0':
        qs = qs.filter(is_paid=False)

    # Totals - calculated on full queryset (no pagination - DataTables handles it client-side)
    agg = qs.aggregate(
        total_revenue=Coalesce(Sum('grand_total'), Decimal('0'), output_field=DecimalField()),
    )

    paid_count = qs.filter(is_paid=True).count()
    unpaid_count = qs.filter(is_paid=False).count()
    total_count = qs.count()

    return render(request, 'services/service_invoice_list.html', {
        'invoices': qs,
        'paid_filter': paid_filter,
        'total_revenue': agg['total_revenue'],
        'paid_count': paid_count,
        'unpaid_count': unpaid_count,
        'total_count': total_count,
    })


# ═══════════════════════════════════════════════════════════════════════════
# SERVICE BUNDLE ITEMS (modal partial)
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_bundle_items(request, bundle_pk):
    """Partial view loaded via data-modal-url to show bundle items."""
    from .models import ServiceBundle
    from django.shortcuts import get_object_or_404
    bundle = get_object_or_404(
        ServiceBundle.objects.select_related('price_list')
        .prefetch_related('price_list__items__item', 'price_list__items__unit'),
        pk=bundle_pk,
    )
    return render(request, 'services/service_bundle_items_modal.html', {'bundle': bundle})


# ═══════════════════════════════════════════════════════════════════════════
# SERVICE INVOICE DETAIL
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_invoice_detail(request, pk):
    """Invoice detail page for service invoices."""
    from core.models import Invoice
    from django.shortcuts import get_object_or_404
    from core.models import BusinessProfile

    inv = get_object_or_404(
        Invoice.objects.prefetch_related(
            'lines', 'payments',
            'customer_services__other_materials',
        ),
        pk=pk,
    )
    profile = BusinessProfile.get_instance()
    today_date = timezone.now().date()

    svc = inv.customer_services.first()
    other_materials_cost = (
        sum((mat.line_total for mat in svc.other_materials.all()), Decimal('0'))
        if svc else Decimal('0')
    )

    # ── Ensure the invoice grand_total reflects the service quotation ──
    # Invoices created before this fix may have the old net-profit figure stored.
    # Recompute and patch the DB record if needed.
    if svc and svc.quotation_amount > 0:
        val = svc.discount_value or Decimal('0')
        if svc.discount_type == 'PERCENT':
            discount_amt = (svc.quotation_amount * val / Decimal('100')).quantize(Decimal('0.01'))
        else:
            discount_amt = val
        correct_grand_total = max(svc.quotation_amount - discount_amt, Decimal('0'))
        correct_subtotal = svc.quotation_amount
        correct_discount = discount_amt

        if inv.grand_total != correct_grand_total or inv.subtotal != correct_subtotal:
            inv.subtotal = correct_subtotal
            inv.discount_total = correct_discount
            inv.grand_total = correct_grand_total
            inv.save(update_fields=['subtotal', 'discount_total', 'grand_total', 'updated_at'])

            # Also fix the invoice lines: replace everything with one quotation line
            from core.models import InvoiceLine
            inv.lines.all().delete()
            InvoiceLine.objects.create(
                invoice=inv,
                item_code='SVC-QUOT',
                item_name=svc.service_name or 'Service',
                qty=Decimal('1'),
                unit='svc',
                unit_price=svc.quotation_amount,
                line_total=svc.quotation_amount,
            )

    # Running balance for payment history
    payments = list(inv.payments.order_by('date', 'created_at'))
    running = inv.grand_total
    payments_with_balance = []
    for p in payments:
        running -= p.amount
        p.balance_after = max(running, 0)
        payments_with_balance.append(p)
    total_paid = sum(p.amount for p in payments)
    balance_due = max(inv.grand_total - total_paid, Decimal('0'))

    return render(request, 'services/service_invoice_detail.html', {
        'invoice': inv,
        'profile': profile,
        'total_paid': total_paid,
        'balance_due': balance_due,
        'payments_with_balance': payments_with_balance,
        'today_date': today_date,
        'service': svc,
        'other_materials_cost': other_materials_cost,
    })


# ═══════════════════════════════════════════════════════════════════════════
# LIST
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_list(request):
    status_filter = request.GET.get('status', '')
    qs = CustomerService.objects.select_related('created_by', 'invoice')
    if status_filter:
        qs = qs.filter(status=status_filter)
    return render(request, 'services/service_list.html', {
        'services': qs,
        'status_filter': status_filter,
        'statuses': ServiceStatus.choices,
    })


# ═══════════════════════════════════════════════════════════════════════════
# DETAIL
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_detail(request, pk):
    svc = get_object_or_404(
        CustomerService.objects.select_related('warehouse', 'created_by', 'posted_by', 'invoice')
        .prefetch_related(
            'lines__item__default_unit', 'lines__item__selling_unit', 'lines__unit', 'lines__location',
            'other_materials',
            Prefetch('bundles', queryset=ServiceBundle.objects.select_related('price_list').prefetch_related(
                'price_list__items__item',
                'price_list__items__unit',
            )),
        ),
        pk=pk,
    )

    try:
        from catalog.utils import get_item_cogs_for_unit as _cogs_fn
    except ImportError:
        _cogs_fn = None

    line_pnl = []
    for line in svc.lines.all():
        if _cogs_fn:
            try:
                # Get COGS per unit in the SAME unit as line.qty (line.unit)
                # This ensures we multiply cost_per_unit × qty in matching units
                cogs_per_unit = _cogs_fn(line.item, line.unit)
            except Exception:
                cogs_per_unit = line.item.cost_price or Decimal('0')
        else:
            cogs_per_unit = line.item.cost_price or Decimal('0')
        cost = cogs_per_unit * line.qty
        is_scrap = getattr(line, 'is_scrap', False)
        line_pnl.append({
            'line': line,
            'cogs_per_unit': cogs_per_unit,
            'cogs': cost,
            'selling': line.line_total,
            'profit': line.line_total - cost,
            'is_scrap': is_scrap,
        })

    scrap_total = sum(
        (row['selling'] for row in line_pnl if row['is_scrap']),
        Decimal('0'),
    )

    # ── Bundle P&L (per-item material COGS) ──────────────────────
    bundle_pnl = []
    total_bundle_material_cogs = Decimal('0')
    for b in svc.bundles.all():
        items_data = []
        b_mat_cogs = Decimal('0')
        b_sets = b.qty or Decimal('1')
        for pli in b.price_list.items.all():
            # Get COGS per unit in the same unit as pli.min_qty
            if _cogs_fn and pli.unit:
                try:
                    cost_pu = _cogs_fn(pli.item, pli.unit)
                except Exception:
                    cost_pu = Decimal(str(pli.item.cost_price or 0))
            else:
                cost_pu = Decimal(str(pli.item.cost_price or 0))
            qty_ps = pli.min_qty or Decimal('1')
            total_qty = qty_ps * b_sets
            price_ps = pli.price or Decimal('0')
            line_charge_total = price_ps * b_sets
            cogs_total = cost_pu * total_qty
            items_data.append({
                'code': pli.item.code,
                'name': pli.item.name,
                'unit': pli.unit.abbreviation if pli.unit_id else '',
                'qty_ps': qty_ps,
                'total_qty': total_qty,
                'price_ps': price_ps,
                'line_charge_total': line_charge_total,
                'cost_pu': cost_pu,
                'cogs_total': cogs_total,
                'profit': line_charge_total - cogs_total,
            })
            b_mat_cogs += cogs_total
        bundle_pnl.append({
            'bundle': b,
            'items': items_data,
            'mat_cogs': b_mat_cogs,
            'bundle_profit': b.bundle_total - b_mat_cogs,
        })
        total_bundle_material_cogs += b_mat_cogs

    # ── P&L summary ───────────────────────────────────
    total_product_selling = sum(
        (r['selling'] for r in line_pnl if not r['is_scrap']), Decimal('0'),
    )
    total_product_cogs = sum(
        (r['cogs'] for r in line_pnl if not r['is_scrap']), Decimal('0'),
    )
    total_other_mat = svc.other_materials_total
    grand_cogs = total_product_cogs + total_bundle_material_cogs + total_other_mat
    gross_profit = svc.quotation_amount - grand_cogs
    roi = (gross_profit / grand_cogs * 100).quantize(Decimal('0.01')) if grand_cogs else Decimal('0')
    total_product_line_profit = total_product_selling - total_product_cogs

    return render(request, 'services/service_detail.html', {
        'service': svc,
        'line_pnl': line_pnl,
        'other_materials': svc.other_materials.all(),
        'scrap_total': scrap_total,
        'bundle_pnl': bundle_pnl,
        'total_product_selling': total_product_selling,
        'total_product_cogs': total_product_cogs,
        'total_product_line_profit': total_product_line_profit,
        'total_bundle_material_cogs': total_bundle_material_cogs,
        'total_other_mat': total_other_mat,
        'grand_cogs': grand_cogs,
        'gross_profit': gross_profit,
        'roi': roi,
    })


# ═══════════════════════════════════════════════════════════════════════════
# CREATE
# ═══════════════════════════════════════════════════════════════════════════
@login_required
@write_denied_for_viewer
def service_create(request):
    if request.method == 'POST':
        form = CustomerServiceForm(request.POST)
        formset = ServiceLineFormSet(request.POST, prefix='lines')
        mat_formset = ServiceOtherMaterialFormSet(request.POST, prefix='mats')
        bundle_formset = ServiceBundleFormSet(request.POST, prefix='bundles')
        form_valid = form.is_valid()
        formset_valid = formset.is_valid()
        mat_valid = mat_formset.is_valid()
        bundle_valid = bundle_formset.is_valid()
        if form_valid and formset_valid and mat_valid and bundle_valid:
            svc = form.save(commit=False)
            svc.created_by = request.user
            if not svc.service_number:
                svc.service_number = CustomerService.generate_next_service_number()
            svc.save()
            formset.instance = svc
            mat_formset.instance = svc
            bundle_formset.instance = svc
            formset.save()
            mat_formset.save()
            bundle_formset.save()
            messages.success(request, f'Service {svc.service_number} created.')
            return redirect('service_detail', pk=svc.pk)
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        next_number = CustomerService.generate_next_service_number()
        form = CustomerServiceForm(initial={'service_number': next_number})
        formset = ServiceLineFormSet(prefix='lines')
        mat_formset = ServiceOtherMaterialFormSet(prefix='mats')
        bundle_formset = ServiceBundleFormSet(prefix='bundles')
    return render(request, 'services/service_form.html', {
        'form': form,
        'formset': formset,
        'mat_formset': mat_formset,
        'bundle_formset': bundle_formset,
        'title': 'New Customer Service',
        'is_create': True,
    })


# ═══════════════════════════════════════════════════════════════════════════
# EDIT
# ═══════════════════════════════════════════════════════════════════════════
@login_required
@write_denied_for_viewer
def service_edit(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if svc.status in (ServiceStatus.COMPLETED, ServiceStatus.CANCELLED):
        messages.error(request, 'Cannot edit a Completed or Cancelled service.')
        return redirect('service_detail', pk=pk)
    if request.method == 'POST':
        form = CustomerServiceEditForm(request.POST, instance=svc)
        formset = ServiceLineFormSet(request.POST, instance=svc, prefix='lines')
        mat_formset = ServiceOtherMaterialFormSet(request.POST, instance=svc, prefix='mats')
        bundle_formset = ServiceBundleFormSet(request.POST, instance=svc, prefix='bundles')
        if form.is_valid() and formset.is_valid() and mat_formset.is_valid() and bundle_formset.is_valid():
            form.save()
            formset.save()
            mat_formset.save()
            bundle_formset.save()
            messages.success(request, f'Service {svc.service_number} updated.')
            return redirect('service_detail', pk=svc.pk)
    else:
        form = CustomerServiceEditForm(instance=svc)
        formset = ServiceLineFormSet(instance=svc, prefix='lines')
        mat_formset = ServiceOtherMaterialFormSet(instance=svc, prefix='mats')
        bundle_formset = ServiceBundleFormSet(instance=svc, prefix='bundles')
    return render(request, 'services/service_form.html', {
        'form': form,
        'formset': formset,
        'mat_formset': mat_formset,
        'bundle_formset': bundle_formset,
        'title': f'Edit Service: {svc.service_number}',
        'service': svc,
        'is_create': False,
    })


# ═══════════════════════════════════════════════════════════════════════════
# DELETE
# ═══════════════════════════════════════════════════════════════════════════
@login_required
@write_denied_for_viewer
def service_delete(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if svc.status == ServiceStatus.COMPLETED:
        messages.error(request, 'Cannot delete a Completed service.')
        return redirect('service_detail', pk=pk)
    if request.method == 'POST':
        svc.delete()
        messages.success(request, 'Service deleted.')
        return redirect('service_list')
    return render(request, 'services/service_delete.html', {'service': svc})


# ═══════════════════════════════════════════════════════════════════════════
# MARK IN-PROGRESS
# ═══════════════════════════════════════════════════════════════════════════
@login_required
@write_denied_for_viewer
def service_start(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if request.method == 'POST':
        if svc.status == ServiceStatus.DRAFT:
            svc.status = ServiceStatus.IN_PROGRESS
            svc.save(update_fields=['status', 'updated_at'])
            messages.success(request, f'Service {svc.service_number} marked as In Progress.')
        else:
            messages.error(request, 'Only DRAFT services can be started.')
    return redirect('service_detail', pk=pk)
# ═══════════════════════════════════════════════════════════════════════════
# COMPLETE — deducts inventory + generates invoice with COGS/ROI
# ═══════════════════════════════════════════════════════════════════════════
@login_required
@transaction.atomic
@write_denied_for_viewer
def service_complete(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if request.method != 'POST':
        return redirect('service_detail', pk=pk)

    if svc.status not in (ServiceStatus.DRAFT, ServiceStatus.IN_PROGRESS):
        messages.error(request, 'Only Draft or In Progress services can be completed.')
        return redirect('service_detail', pk=pk)

    now = timezone.now()
    lines = list(svc.lines.select_related(
        'item__default_unit', 'item__selling_unit',
        'unit', 'location__warehouse',
    ).all())
    other_mats = list(svc.other_materials.all())
    bundles = list(svc.bundles.select_related('price_list').prefetch_related('price_list__items__item', 'price_list__items__unit').all())

    # ── Inventory deduction (Product Lines + Bundles) ──────────────────────
    if lines or bundles:
        try:
            from inventory.models import StockMove, StockBalance, MoveType, MoveStatus
            from catalog.models import convert_to_base_unit
            from warehouses.models import Location

            # ── Check for existing stock movements ──────────────────────────────
            existing_moves = StockMove.objects.filter(
                reference_type='CustomerService',
                reference_id=svc.pk,
                status=MoveStatus.POSTED,
            ).values_list('item_id', flat=True)
            
            existing_item_ids = set(existing_moves)

            default_location = None
            if svc.warehouse_id:
                default_location = (
                    Location.objects
                    .filter(warehouse=svc.warehouse, is_pickable=True)
                    .order_by('code')
                    .first()
                )

            missing_location_items = []
            skipped_unit_items = []
            skipped_existing_items = []
            moves = []

            def deduct_item(item, sale_unit, qty, location):
                # Skip if stock movement already exists for this item
                if item.id in existing_item_ids:
                    skipped_existing_items.append(f"{item.code} (already moved)")
                    return
                    
                try:
                    base_qty = convert_to_base_unit(qty, sale_unit, item.stock_unit, item=item)
                except (ValueError, Exception) as exc:
                    skipped_unit_items.append(
                        f"{item.code} ({qty} {sale_unit.abbreviation} → {item.stock_unit.abbreviation})"
                    )
                    return
                move = StockMove(
                    move_type=MoveType.SERVICE_OUT,
                    item=item,
                    qty=base_qty,
                    unit=item.stock_unit,
                    from_location=location,
                    to_location=None,
                    reference_type='CustomerService',
                    reference_id=svc.pk,
                    reference_number=svc.service_number,
                    batch_number='',
                    serial_number='',
                    status=MoveStatus.POSTED,
                    created_by=request.user,
                    posted_by=request.user,
                    posted_at=now,
                )
                moves.append(move)

                balance, _ = StockBalance.objects.select_for_update().get_or_create(
                    item=item,
                    location=location,
                    defaults={'qty_on_hand': Decimal('0'), 'qty_reserved': Decimal('0')},
                )
                balance.qty_on_hand -= base_qty
                wh = location.warehouse
                if not wh.allow_negative_stock and balance.qty_on_hand < 0:
                    raise ValueError(
                        f"Insufficient stock for {item.code} at {location}. "
                        f"Available: {balance.qty_on_hand + base_qty}, Requested: {base_qty}"
                    )
                balance.save()

            for line in lines:
                if getattr(line, 'is_scrap', False):
                    continue
                location = line.location or default_location
                if location is None:
                    missing_location_items.append(line.item.code)
                    continue
                deduct_item(line.item, line.unit, line.qty, location)

            for bundle in bundles:
                for pli in bundle.price_list.items.select_related('item', 'unit').all():
                    location = default_location
                    if location is None:
                        missing_location_items.append(pli.item.code)
                        continue
                    bundle_qty = (bundle.qty or Decimal('0')) * (pli.min_qty or Decimal('0'))
                    if bundle_qty <= 0:
                        continue
                    deduct_item(pli.item, pli.unit, bundle_qty, location)

            if moves:
                StockMove.objects.bulk_create(moves)

            if missing_location_items:
                messages.warning(
                    request,
                    f'No location set for item(s): {", ".join(sorted(set(missing_location_items)))}. '
                    'Their stock was NOT deducted. Set a location or assign a warehouse.'
                )

            if skipped_existing_items:
                messages.info(
                    request,
                    f'Stock already deducted for: {", ".join(skipped_existing_items)}. '
                    'Only NEW items were processed.'
                )

            if skipped_unit_items:
                messages.warning(
                    request,
                    f'{len(skipped_unit_items)} line(s) skipped due to incompatible units: '
                    f'{", ".join(skipped_unit_items)}. '
                    f'Add the missing Unit Conversions under Catalog → Unit Conversions.'
                )

        except ValueError as exc:
            messages.error(request, f'Stock error: {exc}')
            return redirect('service_detail', pk=pk)

    # ── Generate Invoice ───────────────────────────────────────────────────
    from core.models import Invoice, InvoiceLine, InvoicePayment, PaymentMethod
    from core.views import _next_invoice_number
    import logging
    logger = logging.getLogger(__name__)

    # Invoice amounts are what the CUSTOMER pays — the quoted price (not the net profit).
    if svc.quotation_amount > 0:
        # Customer pays the quotation. Discount is applied to the quotation.
        val = svc.discount_value or Decimal('0')
        if svc.discount_type == 'PERCENT':
            discount_amt = (svc.quotation_amount * val / Decimal('100')).quantize(Decimal('0.01'))
        else:
            discount_amt = val
        subtotal = svc.quotation_amount
        grand_total = max(subtotal - discount_amt, Decimal('0'))
    else:
        # No quotation — charge whatever the individual lines total
        subtotal = svc.product_lines_total + svc.other_materials_total + svc.bundles_total
        discount_amt = svc.discount_amount
        grand_total = max(subtotal - discount_amt, Decimal('0'))

    partial_paid = svc.partial_payment_amount_value
    if partial_paid > grand_total:
        partial_paid = grand_total
    
    # Calculate remaining balance after partial payment
    # This ensures we don't double-count revenue in P&L
    remaining_balance = max(grand_total - partial_paid, Decimal('0'))
    
    # Determine invoice amounts based on whether there was a partial payment
    if partial_paid > 0:
        # Invoice shows only the remaining balance
        invoice_subtotal = remaining_balance
        invoice_discount = Decimal('0')  # Discount already applied in grand_total calculation
        invoice_grand_total = remaining_balance
        invoice_notes = f'Service: {svc.service_name} (Remaining balance after ₱{partial_paid:,.2f} partial payment)'
    else:
        # No partial payment, invoice shows full amount
        invoice_subtotal = subtotal
        invoice_discount = discount_amt
        invoice_grand_total = grand_total
        invoice_notes = f'Service: {svc.service_name}'

    # ── Check for existing invoice and UPDATE or CREATE ───────────────────
    existing_invoice = None
    if svc.invoice_id:
        # Service already has an invoice linked, update it
        existing_invoice = Invoice.objects.select_for_update().filter(
            pk=svc.invoice_id,
            is_void=False
        ).first()
    
    if existing_invoice:
        logger.info(f"Found existing invoice {existing_invoice.invoice_number} for service {svc.service_number}, updating it")
        
        # Get existing invoice line item codes to avoid duplicates
        existing_line_items = set(
            existing_invoice.lines.values_list('item_code', flat=True)
        )
        
        new_lines_added = 0
        
        # Update invoice header
        existing_invoice.subtotal = invoice_subtotal
        existing_invoice.discount_total = invoice_discount
        existing_invoice.grand_total = invoice_grand_total
        existing_invoice.notes = invoice_notes
        existing_invoice.customer_name = svc.customer_name
        existing_invoice.customer_address = svc.address
        existing_invoice.save(update_fields=[
            'subtotal', 'discount_total', 'grand_total', 'notes',
            'customer_name', 'customer_address', 'updated_at'
        ])
        
        # Add new invoice lines based on service type
        if svc.quotation_amount > 0:
            # Quotation-based: Update or create the single service line
            if 'SVC-QUOT' not in existing_line_items:
                line_description = svc.service_name or 'Service'
                if partial_paid > 0:
                    line_description += f' (Balance after ₱{partial_paid:,.2f} partial payment)'
                
                InvoiceLine.objects.create(
                    invoice=existing_invoice,
                    item_code='SVC-QUOT',
                    item_name=line_description,
                    qty=Decimal('1'),
                    unit='svc',
                    unit_price=invoice_grand_total,
                    line_total=invoice_grand_total,
                )
                new_lines_added += 1
                logger.info(f"Added quotation line to invoice {existing_invoice.invoice_number}")
        else:
            # Item-based: Add new product lines
            for line in lines:
                if line.item.code not in existing_line_items:
                    InvoiceLine.objects.create(
                        invoice=existing_invoice,
                        item_code=line.item.code,
                        item_name=line.item.name,
                        qty=line.qty,
                        unit=line.unit.abbreviation,
                        unit_price=line.unit_price,
                        line_total=line.line_total,
                    )
                    new_lines_added += 1
                    logger.info(f"Added item {line.item.code} to invoice {existing_invoice.invoice_number}")

            # Add new other materials
            for mat in other_mats:
                mat_key = f"MAT-{mat.item_name}"
                if mat_key not in existing_line_items:
                    InvoiceLine.objects.create(
                        invoice=existing_invoice,
                        item_code='MAT',
                        item_name=mat.item_name,
                        qty=mat.qty,
                        unit='unit',
                        unit_price=mat.unit_price,
                        line_total=mat.line_total,
                    )
                    new_lines_added += 1
                    logger.info(f"Added material {mat.item_name} to invoice {existing_invoice.invoice_number}")

            # If no lines and no materials, add service line
            if not lines and not other_mats and 'SVC' not in existing_line_items:
                InvoiceLine.objects.create(
                    invoice=existing_invoice,
                    item_code='SVC',
                    item_name=svc.service_name,
                    qty=Decimal('1'),
                    unit='svc',
                    unit_price=grand_total,
                    line_total=grand_total,
                )
                new_lines_added += 1
                logger.info(f"Added service line to invoice {existing_invoice.invoice_number}")
        
        logger.info(f"Updated invoice {existing_invoice.invoice_number} with {new_lines_added} new line(s)")
        inv = existing_invoice
        inv._was_updated = True
        inv._new_lines_count = new_lines_added
    else:
        # No existing invoice, create new one
        logger.info(f"No existing invoice found for service {svc.service_number}, creating new one")
        
        inv = Invoice.objects.create(
            invoice_number=_next_invoice_number(),
            date=now.date(),
            customer_name=svc.customer_name,
            customer_address=svc.address,
            subtotal=invoice_subtotal,
            discount_total=invoice_discount,
            grand_total=invoice_grand_total,
            grand_total_cogs=Decimal('0'),
            notes=invoice_notes,
            created_by=request.user,
        )

        # ── Invoice lines (what the customer sees) ────────────────────────────
        # If there's a quotation, the customer is billed for the quoted amount only.
        # Material/part costs are internal COGS and do not appear as customer line items.
        if svc.quotation_amount > 0:
            # Show the remaining balance amount (after partial payment)
            line_description = svc.service_name or 'Service'
            if partial_paid > 0:
                line_description += f' (Balance after ₱{partial_paid:,.2f} partial payment)'
            
            InvoiceLine.objects.create(
                invoice=inv,
                item_code='SVC-QUOT',
                item_name=line_description,
                qty=Decimal('1'),
                unit='svc',
                unit_price=invoice_grand_total,
                line_total=invoice_grand_total,
            )
        else:
            # No quotation — show individual product/material lines
            for line in lines:
                InvoiceLine.objects.create(
                    invoice=inv,
                    item_code=line.item.code,
                    item_name=line.item.name,
                    qty=line.qty,
                    unit=line.unit.abbreviation,
                    unit_price=line.unit_price,
                    line_total=line.line_total,
                )

            for mat in other_mats:
                InvoiceLine.objects.create(
                    invoice=inv,
                    item_code='MAT',
                    item_name=mat.item_name,
                    qty=mat.qty,
                    unit='unit',
                    unit_price=mat.unit_price,
                    line_total=mat.line_total,
                )

            if not lines and not other_mats:
                InvoiceLine.objects.create(
                    invoice=inv,
                    item_code='SVC',
                    item_name=svc.service_name,
                    qty=Decimal('1'),
                    unit='svc',
                    unit_price=grand_total,
                    line_total=grand_total,
                )
        
        inv._was_updated = False
        inv._was_updated = False

    # ── Handle payments ────────────────────────────────────────────────────
    if svc.payment_status == ServicePaymentStatus.PAID and invoice_grand_total > 0:
        # If already marked as paid, create payment for the remaining balance
        final_payment = invoice_grand_total
    else:
        final_payment = Decimal('0')

    if final_payment > 0:
        InvoicePayment.objects.create(
            invoice=inv,
            date=now.date(),
            method=PaymentMethod.CASH,
            amount=final_payment,
            reference_no='',
            notes=f'Final payment for service {svc.service_number}',
            created_by=request.user,
        )

    if final_payment >= invoice_grand_total and invoice_grand_total > 0:
        inv.is_paid = True
        inv.paid_at = now
        inv.paid_date = now.date()
        inv.save(update_fields=['is_paid', 'paid_at', 'paid_date', 'updated_at'])

    # ── Mark service completed ─────────────────────────────────────────────
    svc.status = ServiceStatus.COMPLETED
    svc.invoice = inv
    svc.posted_by = request.user
    svc.posted_at = now
    if not svc.completion_date:
        svc.completion_date = now.date()
    svc.save(update_fields=[
        'status', 'invoice', 'posted_by', 'posted_at',
        'completion_date', 'updated_at',
    ])

    # Recompute COGS now that svc.invoice FK is committed so that
    # service_invoice_cogs can traverse the reverse relation and correctly
    # sum product lines (non-scrap), bundle lines, and other materials.
    try:
        from core.cogs import compute_invoice_cogs
        computed_cogs = compute_invoice_cogs(inv)
        inv.grand_total_cogs = computed_cogs
        inv.save(update_fields=['grand_total_cogs', 'updated_at'])
    except Exception:
        pass

    if partial_paid > 0 and partial_paid < grand_total:
        if getattr(inv, '_was_updated', False):
            messages.success(
                request,
                f'Service {svc.service_number} completed. Invoice {inv.invoice_number} updated with {getattr(inv, "_new_lines_count", 0)} new item(s). Partial payment of ₱{partial_paid:,.2f} applied.'
            )
        else:
            messages.success(
                request,
                f'Service {svc.service_number} completed. Invoice {inv.invoice_number} generated with partial payment of ₱{partial_paid:,.2f}.'
            )
    elif partial_paid >= grand_total and grand_total > 0:
        if getattr(inv, '_was_updated', False):
            messages.success(
                request,
                f'Service {svc.service_number} completed. Invoice {inv.invoice_number} updated with {getattr(inv, "_new_lines_count", 0)} new item(s) and marked fully paid.'
            )
        else:
            messages.success(
                request,
                f'Service {svc.service_number} completed. Invoice {inv.invoice_number} generated and marked fully paid.'
            )
    else:
        if getattr(inv, '_was_updated', False):
            messages.success(
                request,
                f'Service {svc.service_number} completed. Invoice {inv.invoice_number} updated with {getattr(inv, "_new_lines_count", 0)} new item(s).'
            )
        else:
            messages.success(
                request,
                f'Service {svc.service_number} completed. Invoice {inv.invoice_number} generated.'
            )
    return redirect('service_detail', pk=pk)


# ═══════════════════════════════════════════════════════════════════════════
# CANCEL
# ═══════════════════════════════════════════════════════════════════════════
@login_required
@write_denied_for_viewer
def service_cancel(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if request.method == 'POST':
        if svc.status in (ServiceStatus.DRAFT, ServiceStatus.IN_PROGRESS):
            svc.status = ServiceStatus.CANCELLED
            svc.save(update_fields=['status', 'updated_at'])
            messages.success(request, f'Service {svc.service_number} cancelled.')
        else:
            messages.error(request, 'Cannot cancel a Completed service.')
    return redirect('service_detail', pk=pk)
