from decimal import Decimal
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from django.db.models import Prefetch
from django.utils import timezone

from services.models import CustomerService, ServiceLine, ServiceOtherMaterial, ServiceBundle, ServiceStatus, ServicePaymentStatus
from services.forms import (
    CustomerServiceForm, CustomerServiceEditForm,
    ServiceLineFormSet, ServiceOtherMaterialFormSet, ServiceBundleFormSet,
)


# ═══════════════════════════════════════════════════════════════════════════
# SERVICE INVOICE LIST
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_invoice_list(request):
    """List all invoices generated by customer services (service-type only)."""
    from core.models import Invoice
    from django.db.models import Sum, Q
    from django.db.models.functions import Coalesce
    from django.db.models import DecimalField

    # Invoices that have at least one linked customer service
    invoice_ids = CustomerService.objects.filter(
        invoice__isnull=False
    ).values_list('invoice_id', flat=True).distinct()

    qs = Invoice.objects.filter(pk__in=invoice_ids).select_related(
        'created_by'
    ).prefetch_related('customer_services', 'payments').order_by('-date')

    # Optional filters
    paid_filter = request.GET.get('paid', '')
    if paid_filter == '1':
        qs = qs.filter(is_paid=True)
    elif paid_filter == '0':
        qs = qs.filter(is_paid=False)

    # Totals
    agg = qs.aggregate(
        total_revenue=Coalesce(Sum('grand_total'), Decimal('0'), output_field=DecimalField()),
    )

    return render(request, 'services/service_invoice_list.html', {
        'invoices': qs,
        'paid_filter': paid_filter,
        'total_revenue': agg['total_revenue'],
    })


# ═══════════════════════════════════════════════════════════════════════════
# SERVICE BUNDLE ITEMS (modal partial)
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_bundle_items(request, bundle_pk):
    """Partial view loaded via data-modal-url to show bundle items."""
    from .models import ServiceBundle
    from django.shortcuts import get_object_or_404
    bundle = get_object_or_404(
        ServiceBundle.objects.select_related('price_list')
        .prefetch_related('price_list__items__item', 'price_list__items__unit'),
        pk=bundle_pk,
    )
    return render(request, 'services/service_bundle_items_modal.html', {'bundle': bundle})


# ═══════════════════════════════════════════════════════════════════════════
# SERVICE INVOICE DETAIL
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_invoice_detail(request, pk):
    """Invoice detail page for service invoices."""
    from core.models import Invoice
    from django.shortcuts import get_object_or_404
    from core.models import BusinessProfile

    inv = get_object_or_404(
        Invoice.objects.prefetch_related('lines', 'payments', 'customer_services'),
        pk=pk,
    )
    profile = BusinessProfile.get_instance()
    today_date = timezone.now().date()

    svc = inv.customer_services.first()

    # ── Ensure the invoice grand_total reflects the service quotation ──
    # Invoices created before this fix may have the old net-profit figure stored.
    # Recompute and patch the DB record if needed.
    if svc and svc.quotation_amount > 0:
        val = svc.discount_value or Decimal('0')
        if svc.discount_type == 'PERCENT':
            discount_amt = (svc.quotation_amount * val / Decimal('100')).quantize(Decimal('0.01'))
        else:
            discount_amt = val
        correct_grand_total = max(svc.quotation_amount - discount_amt, Decimal('0'))
        correct_subtotal = svc.quotation_amount
        correct_discount = discount_amt

        if inv.grand_total != correct_grand_total or inv.subtotal != correct_subtotal:
            inv.subtotal = correct_subtotal
            inv.discount_total = correct_discount
            inv.grand_total = correct_grand_total
            inv.save(update_fields=['subtotal', 'discount_total', 'grand_total', 'updated_at'])

            # Also fix the invoice lines: replace everything with one quotation line
            from core.models import InvoiceLine
            inv.lines.all().delete()
            InvoiceLine.objects.create(
                invoice=inv,
                item_code='SVC-QUOT',
                item_name=svc.service_name or 'Service',
                qty=Decimal('1'),
                unit='svc',
                unit_price=svc.quotation_amount,
                line_total=svc.quotation_amount,
            )

    # Running balance for payment history
    payments = list(inv.payments.order_by('date', 'created_at'))
    running = inv.grand_total
    payments_with_balance = []
    for p in payments:
        running -= p.amount
        p.balance_after = max(running, 0)
        payments_with_balance.append(p)
    total_paid = sum(p.amount for p in payments)
    balance_due = max(inv.grand_total - total_paid, Decimal('0'))

    return render(request, 'services/service_invoice_detail.html', {
        'invoice': inv,
        'profile': profile,
        'total_paid': total_paid,
        'balance_due': balance_due,
        'payments_with_balance': payments_with_balance,
        'today_date': today_date,
        'service': svc,
    })


# ═══════════════════════════════════════════════════════════════════════════
# LIST
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_list(request):
    status_filter = request.GET.get('status', '')
    qs = CustomerService.objects.select_related('created_by', 'invoice')
    if status_filter:
        qs = qs.filter(status=status_filter)
    return render(request, 'services/service_list.html', {
        'services': qs,
        'status_filter': status_filter,
        'statuses': ServiceStatus.choices,
    })


# ═══════════════════════════════════════════════════════════════════════════
# DETAIL
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_detail(request, pk):
    svc = get_object_or_404(
        CustomerService.objects.select_related('warehouse', 'created_by', 'posted_by', 'invoice')
        .prefetch_related(
            'lines__item__default_unit', 'lines__item__selling_unit', 'lines__unit', 'lines__location',
            'other_materials',
            Prefetch('bundles', queryset=ServiceBundle.objects.select_related('price_list').prefetch_related('price_list__items')),
        ),
        pk=pk,
    )

    try:
        from catalog.models import get_cost_for_unit as _cogs_fn
    except ImportError:
        _cogs_fn = None

    line_pnl = []
    for line in svc.lines.all():
        if _cogs_fn:
            try:
                cogs_per_unit = _cogs_fn(line.item, line.unit)
            except Exception:
                cogs_per_unit = line.item.cost_price or Decimal('0')
        else:
            cogs_per_unit = line.item.cost_price or Decimal('0')
        cost = cogs_per_unit * line.qty
        line_pnl.append({
            'line': line,
            'cogs_per_unit': cogs_per_unit,
            'cogs': cost,
            'selling': line.line_total,
            'profit': line.line_total - cost,
        })

    return render(request, 'services/service_detail.html', {
        'service': svc,
        'line_pnl': line_pnl,
        'other_materials': svc.other_materials.all(),
    })


# ═══════════════════════════════════════════════════════════════════════════
# CREATE
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_create(request):
    if request.method == 'POST':
        form = CustomerServiceForm(request.POST)
        formset = ServiceLineFormSet(request.POST, prefix='lines')
        mat_formset = ServiceOtherMaterialFormSet(request.POST, prefix='mats')
        bundle_formset = ServiceBundleFormSet(request.POST, prefix='bundles')
        if form.is_valid():
            svc = form.save(commit=False)
            svc.created_by = request.user
            svc.save()
            formset = ServiceLineFormSet(request.POST, instance=svc, prefix='lines')
            mat_formset = ServiceOtherMaterialFormSet(request.POST, instance=svc, prefix='mats')
            bundle_formset = ServiceBundleFormSet(request.POST, instance=svc, prefix='bundles')
            if formset.is_valid() and mat_formset.is_valid() and bundle_formset.is_valid():
                formset.save()
                mat_formset.save()
                bundle_formset.save()
                messages.success(request, f'Service {svc.service_number} created.')
                return redirect('service_detail', pk=svc.pk)
    else:
        form = CustomerServiceForm()
        formset = ServiceLineFormSet(prefix='lines')
        mat_formset = ServiceOtherMaterialFormSet(prefix='mats')
        bundle_formset = ServiceBundleFormSet(prefix='bundles')
    return render(request, 'services/service_form.html', {
        'form': form,
        'formset': formset,
        'mat_formset': mat_formset,
        'bundle_formset': bundle_formset,
        'title': 'New Customer Service',
        'is_create': True,
    })


# ═══════════════════════════════════════════════════════════════════════════
# EDIT
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_edit(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if svc.status in (ServiceStatus.COMPLETED, ServiceStatus.CANCELLED):
        messages.error(request, 'Cannot edit a Completed or Cancelled service.')
        return redirect('service_detail', pk=pk)
    if request.method == 'POST':
        form = CustomerServiceEditForm(request.POST, instance=svc)
        formset = ServiceLineFormSet(request.POST, instance=svc, prefix='lines')
        mat_formset = ServiceOtherMaterialFormSet(request.POST, instance=svc, prefix='mats')
        bundle_formset = ServiceBundleFormSet(request.POST, instance=svc, prefix='bundles')
        if form.is_valid() and formset.is_valid() and mat_formset.is_valid() and bundle_formset.is_valid():
            form.save()
            formset.save()
            mat_formset.save()
            bundle_formset.save()
            messages.success(request, f'Service {svc.service_number} updated.')
            return redirect('service_detail', pk=svc.pk)
    else:
        form = CustomerServiceEditForm(instance=svc)
        formset = ServiceLineFormSet(instance=svc, prefix='lines')
        mat_formset = ServiceOtherMaterialFormSet(instance=svc, prefix='mats')
        bundle_formset = ServiceBundleFormSet(instance=svc, prefix='bundles')
    return render(request, 'services/service_form.html', {
        'form': form,
        'formset': formset,
        'mat_formset': mat_formset,
        'bundle_formset': bundle_formset,
        'title': f'Edit Service: {svc.service_number}',
        'service': svc,
        'is_create': False,
    })


# ═══════════════════════════════════════════════════════════════════════════
# DELETE
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_delete(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if svc.status == ServiceStatus.COMPLETED:
        messages.error(request, 'Cannot delete a Completed service.')
        return redirect('service_detail', pk=pk)
    if request.method == 'POST':
        svc.delete()
        messages.success(request, 'Service deleted.')
        return redirect('service_list')
    return render(request, 'services/service_delete.html', {'service': svc})


# ═══════════════════════════════════════════════════════════════════════════
# MARK IN-PROGRESS
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_start(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if request.method == 'POST':
        if svc.status == ServiceStatus.DRAFT:
            svc.status = ServiceStatus.IN_PROGRESS
            svc.save(update_fields=['status', 'updated_at'])
            messages.success(request, f'Service {svc.service_number} marked as In Progress.')
        else:
            messages.error(request, 'Only DRAFT services can be started.')
    return redirect('service_detail', pk=pk)
# ═══════════════════════════════════════════════════════════════════════════
# COMPLETE — deducts inventory + generates invoice with COGS/ROI
# ═══════════════════════════════════════════════════════════════════════════
@login_required
@transaction.atomic
def service_complete(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if request.method != 'POST':
        return redirect('service_detail', pk=pk)

    if svc.status not in (ServiceStatus.DRAFT, ServiceStatus.IN_PROGRESS):
        messages.error(request, 'Only Draft or In Progress services can be completed.')
        return redirect('service_detail', pk=pk)

    now = timezone.now()
    lines = list(svc.lines.select_related(
        'item__default_unit', 'item__selling_unit',
        'unit', 'location__warehouse',
    ).all())
    other_mats = list(svc.other_materials.all())
    bundles = list(svc.bundles.select_related('price_list').prefetch_related('price_list__items__item', 'price_list__items__unit').all())

    # ── Inventory deduction (Product Lines + Bundles) ──────────────────────
    if lines or bundles:
        try:
            from inventory.models import StockMove, StockBalance, MoveType, MoveStatus
            from catalog.models import convert_to_base_unit
            from warehouses.models import Location

            default_location = None
            if svc.warehouse_id:
                default_location = (
                    Location.objects
                    .filter(warehouse=svc.warehouse, is_pickable=True)
                    .order_by('code')
                    .first()
                )

            missing_location_items = []
            moves = []

            def deduct_item(item, sale_unit, qty, location):
                base_qty = convert_to_base_unit(qty, sale_unit, item.stock_unit, item=item)
                move = StockMove(
                    move_type=MoveType.SERVICE_OUT,
                    item=item,
                    qty=base_qty,
                    unit=item.stock_unit,
                    from_location=location,
                    to_location=None,
                    reference_type='CustomerService',
                    reference_id=svc.pk,
                    reference_number=svc.service_number,
                    batch_number='',
                    serial_number='',
                    status=MoveStatus.POSTED,
                    created_by=request.user,
                    posted_by=request.user,
                    posted_at=now,
                )
                moves.append(move)

                balance, _ = StockBalance.objects.select_for_update().get_or_create(
                    item=item,
                    location=location,
                    defaults={'qty_on_hand': Decimal('0'), 'qty_reserved': Decimal('0')},
                )
                balance.qty_on_hand -= base_qty
                wh = location.warehouse
                if not wh.allow_negative_stock and balance.qty_on_hand < 0:
                    raise ValueError(
                        f"Insufficient stock for {item.code} at {location}. "
                        f"Available: {balance.qty_on_hand + base_qty}, Requested: {base_qty}"
                    )
                balance.save()

            for line in lines:
                location = line.location or default_location
                if location is None:
                    missing_location_items.append(line.item.code)
                    continue
                deduct_item(line.item, line.unit, line.qty, location)

            for bundle in bundles:
                for pli in bundle.price_list.items.select_related('item', 'unit').all():
                    location = default_location
                    if location is None:
                        missing_location_items.append(pli.item.code)
                        continue
                    bundle_qty = (bundle.qty or Decimal('0')) * (pli.min_qty or Decimal('0'))
                    if bundle_qty <= 0:
                        continue
                    deduct_item(pli.item, pli.unit, bundle_qty, location)

            if moves:
                StockMove.objects.bulk_create(moves)

            if missing_location_items:
                messages.warning(
                    request,
                    f'No location set for item(s): {", ".join(sorted(set(missing_location_items)))}. '
                    'Their stock was NOT deducted. Set a location or assign a warehouse.'
                )

        except ValueError as exc:
            messages.error(request, f'Stock error: {exc}')
            return redirect('service_detail', pk=pk)

    # ── Compute COGS for invoice ───────────────────────────────────────────
    try:
        from catalog.utils import get_item_cogs_for_unit
        _cogs_fn = get_item_cogs_for_unit
    except ImportError:
        _cogs_fn = None

    total_cogs = Decimal('0')
    for line in lines:
        if _cogs_fn:
            try:
                cogs_pu = _cogs_fn(line.item, line.unit)
            except Exception:
                cogs_pu = line.item.cost_price or Decimal('0')
        else:
            cogs_pu = line.item.cost_price or Decimal('0')
        total_cogs += cogs_pu * line.qty

    for bundle in bundles:
        for pli in bundle.price_list.items.select_related('item', 'unit').all():
            if _cogs_fn:
                try:
                    bundle_cogs_pu = _cogs_fn(pli.item, pli.unit)
                except Exception:
                    bundle_cogs_pu = pli.item.cost_price or Decimal('0')
            else:
                bundle_cogs_pu = pli.item.cost_price or Decimal('0')
            bundle_qty = (bundle.qty or Decimal('0')) * (pli.min_qty or Decimal('0'))
            total_cogs += bundle_cogs_pu * bundle_qty

    # Other materials: their unit_price is treated as cost (no catalog reference)
    for mat in other_mats:
        total_cogs += mat.line_total

    # ── Generate Invoice ───────────────────────────────────────────────────
    from core.models import Invoice, InvoiceLine, InvoicePayment, PaymentMethod
    from core.views import _next_invoice_number

    # Invoice amounts are what the CUSTOMER pays — the quoted price (not the net profit).
    if svc.quotation_amount > 0:
        # Customer pays the quotation. Discount is applied to the quotation.
        val = svc.discount_value or Decimal('0')
        if svc.discount_type == 'PERCENT':
            discount_amt = (svc.quotation_amount * val / Decimal('100')).quantize(Decimal('0.01'))
        else:
            discount_amt = val
        subtotal = svc.quotation_amount
        grand_total = max(subtotal - discount_amt, Decimal('0'))
    else:
        # No quotation — charge whatever the individual lines total
        subtotal = svc.product_lines_total + svc.other_materials_total + svc.bundles_total
        discount_amt = svc.discount_amount
        grand_total = max(subtotal - discount_amt, Decimal('0'))

    partial_paid = svc.partial_payment_amount_value
    if partial_paid > grand_total:
        partial_paid = grand_total

    inv = Invoice.objects.create(
        invoice_number=_next_invoice_number(),
        date=now.date(),
        customer_name=svc.customer_name,
        customer_address=svc.address,
        subtotal=subtotal,
        discount_total=discount_amt,
        grand_total=grand_total,
        grand_total_cogs=total_cogs,
        notes=f'Service: {svc.service_name}',
        created_by=request.user,
    )

    if svc.payment_status == ServicePaymentStatus.PAID and grand_total > 0:
        partial_paid = grand_total

    if partial_paid > 0:
        InvoicePayment.objects.create(
            invoice=inv,
            date=now.date(),
            method=PaymentMethod.CASH,
            amount=partial_paid,
            reference_no='',
            notes=f'Initial payment recorded from service {svc.service_number}',
            created_by=request.user,
        )

    if partial_paid >= grand_total and grand_total > 0:
        inv.is_paid = True
        inv.paid_at = now
        inv.paid_date = now.date()
        inv.save(update_fields=['is_paid', 'paid_at', 'paid_date', 'updated_at'])

    # ── Invoice lines (what the customer sees) ────────────────────────────
    # If there's a quotation, the customer is billed for the quoted amount only.
    # Material/part costs are internal COGS and do not appear as customer line items.
    if svc.quotation_amount > 0:
        InvoiceLine.objects.create(
            invoice=inv,
            item_code='SVC-QUOT',
            item_name=svc.service_name or 'Service',
            qty=Decimal('1'),
            unit='svc',
            unit_price=svc.quotation_amount,
            line_total=svc.quotation_amount,
        )
    else:
        # No quotation — show individual product/material lines
        for line in lines:
            InvoiceLine.objects.create(
                invoice=inv,
                item_code=line.item.code,
                item_name=line.item.name,
                qty=line.qty,
                unit=line.unit.abbreviation,
                unit_price=line.unit_price,
                line_total=line.line_total,
            )

        for mat in other_mats:
            InvoiceLine.objects.create(
                invoice=inv,
                item_code='MAT',
                item_name=mat.item_name,
                qty=mat.qty,
                unit='unit',
                unit_price=mat.unit_price,
                line_total=mat.line_total,
            )

        if not lines and not other_mats:
            InvoiceLine.objects.create(
                invoice=inv,
                item_code='SVC',
                item_name=svc.service_name,
                qty=Decimal('1'),
                unit='svc',
                unit_price=grand_total,
                line_total=grand_total,
            )

    # ── Mark service completed ─────────────────────────────────────────────
    svc.status = ServiceStatus.COMPLETED
    svc.invoice = inv
    svc.posted_by = request.user
    svc.posted_at = now
    if not svc.completion_date:
        svc.completion_date = now.date()
    svc.save(update_fields=[
        'status', 'invoice', 'posted_by', 'posted_at',
        'completion_date', 'updated_at',
    ])

    if partial_paid > 0 and partial_paid < grand_total:
        messages.success(
            request,
            f'Service {svc.service_number} completed. Invoice {inv.invoice_number} generated with partial payment of ₱{partial_paid:,.2f}.'
        )
    elif partial_paid >= grand_total and grand_total > 0:
        messages.success(
            request,
            f'Service {svc.service_number} completed. Invoice {inv.invoice_number} generated and marked fully paid.'
        )
    else:
        messages.success(
            request,
            f'Service {svc.service_number} completed. Invoice {inv.invoice_number} generated.'
        )
    return redirect('service_detail', pk=pk)


# ═══════════════════════════════════════════════════════════════════════════
# CANCEL
# ═══════════════════════════════════════════════════════════════════════════
@login_required
def service_cancel(request, pk):
    svc = get_object_or_404(CustomerService, pk=pk)
    if request.method == 'POST':
        if svc.status in (ServiceStatus.DRAFT, ServiceStatus.IN_PROGRESS):
            svc.status = ServiceStatus.CANCELLED
            svc.save(update_fields=['status', 'updated_at'])
            messages.success(request, f'Service {svc.service_number} cancelled.')
        else:
            messages.error(request, 'Cannot cancel a Completed service.')
    return redirect('service_detail', pk=pk)
