# Generated by Django 6.0.2 on 2026-02-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='move_type',
            field=models.CharField(choices=[('RECEIVE', 'Receive'), ('DELIVER', 'Deliver'), ('TRANSFER', 'Transfer'), ('ADJUST', 'Adjustment'), ('DAMAGE', 'Damage'), ('RETURN_IN', 'Return (In)'), ('RETURN_OUT', 'Return (Out)'), ('POS_SALE', 'POS Sale')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['location', 'item'], name='inventory_s_locatio_a9b811_idx'),
        ),
    ]
