# Generated by Django 5.2.6 on 2026-03-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supplymovement_batch_number_supplymovement_reference'),
        ('inventory', '0003_damagedreportline_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytosupplytransferline',
            name='supply_item',
            field=models.ForeignKey(blank=True, help_text='Optional: Supply item to credit. If blank, will auto-create/find based on catalog item.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.supplyitem'),
        ),
    ]
