# Generated by Django 6.0.2 on 2026-03-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_make_supply_item_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='move_type',
            field=models.CharField(choices=[('RECEIVE', 'Receive'), ('DELIVER', 'Deliver'), ('TRANSFER', 'Transfer'), ('ADJUST', 'Adjustment'), ('DAMAGE', 'Damage'), ('RETURN_IN', 'Return (In)'), ('RETURN_OUT', 'Return (Out)'), ('POS_SALE', 'POS Sale'), ('SUPPLY_OUT', 'Supply Out'), ('SERVICE_OUT', 'Service Out')], db_index=True, max_length=20),
        ),
    ]
