# Generated by Django 5.2.6 on 2026-09-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockmove_move_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagedreport',
            name='damage_date',
            field=models.DateField(blank=True, help_text='Date when the damage occurred', null=True),
        ),
    ]
