# Generated by Django 6.0.2 on 2026-02-12 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
        ('pos', '0001_initial'),
        ('pricing', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posregister',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_registers', to='pricing.pricelist'),
        ),
        migrations.AddField(
            model_name='posregister',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_registers', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='possale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='partners.customer'),
        ),
        migrations.AddField(
            model_name='possale',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to='warehouses.location'),
        ),
        migrations.AddField(
            model_name='possale',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possale',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pos.posregister'),
        ),
        migrations.AddField(
            model_name='possale',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='posrefund',
            name='original_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='pos.possale'),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.possale'),
        ),
        migrations.AddField(
            model_name='possaleline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item'),
        ),
        migrations.AddField(
            model_name='possaleline',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.location'),
        ),
        migrations.AddField(
            model_name='possaleline',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.possale'),
        ),
        migrations.AddField(
            model_name='possaleline',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit'),
        ),
        migrations.AddField(
            model_name='posrefundline',
            name='sale_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.possaleline'),
        ),
        migrations.AddField(
            model_name='posshift',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_shifts_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posshift',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_shifts_opened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posshift',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='pos.posregister'),
        ),
        migrations.AddField(
            model_name='possale',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pos.posshift'),
        ),
        migrations.AddField(
            model_name='posrefund',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='pos.posshift'),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_entries', to='pos.posshift'),
        ),
    ]
