# Generated by Django 6.0.2 on 2026-02-14 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='Sales channel (Physical Store, Facebook, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='core.saleschannel'),
        ),
    ]
