# Generated by Django 6.0.2 on 2026-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_possale_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
