# Generated by Django 6.0.2 on 2026-03-26 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_possale_stock_deducted'),
        ('pricing', '0003_customerpricecatalog_effective_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSaleBundleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_sets', models.DecimalField(decimal_places=4, default=1, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sale_bundle_lines', to='pricing.pricelist')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_lines', to='pos.possale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
