# Generated by Django 5.2.6 on 2026-07-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_add_pos_sale_bundle_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='posrefund',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('BANK', 'Bank Transfer'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH', help_text='How the refund was given back — determines whether it counts against the cash drawer at shift close.', max_length=10),
        ),
        migrations.AddField(
            model_name='posshift',
            name='cash_refund_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Refunds given back in cash only — this (not refund_total) is what reduces the cash drawer.', max_digits=15),
        ),
    ]
