# Generated by Django 5.2.6 on 2026-07-13 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_posrefund_method_posshift_cash_refund_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posrefundline',
            name='sale_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_lines', to='pos.possaleline'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PAID', 'Paid'), ('POSTED', 'Posted'), ('VOID', 'Void'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('REFUNDED', 'Refunded')], default='DRAFT', max_length=20),
        ),
    ]
