# Generated by Django 5.2.6 on 2026-04-30 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created Record'), ('UPDATE', 'Updated Record'), ('DELETE', 'Deleted Record'), ('FIX', 'Data Fix / Correction'), ('MIGRATE', 'Data Migration'), ('ADMIN', 'Django Admin Change'), ('SHELL', 'Shell / Script Change'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('table_name', models.CharField(db_index=True, help_text='Database table or model name affected (e.g. catalog_item, StockBalance)', max_length=100)),
                ('record_id', models.CharField(blank=True, default='', help_text='ID or identifier of the affected record(s). Use comma for multiple.', max_length=100)),
                ('fields_changed', models.TextField(blank=True, default='', help_text='Which fields were changed (e.g. cost_price, qty_on_hand, status)')),
                ('old_value', models.TextField(blank=True, default='', help_text='Previous value(s) before the change')),
                ('new_value', models.TextField(blank=True, default='', help_text='New value(s) after the change')),
                ('reason', models.TextField(help_text='Why this change was made — be specific')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional context, ticket numbers, or references')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
