# Generated by Django 6.0.2 on 2026-02-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Weighted average cost used for COGS and profit margin calculations.', max_digits=15),
        ),
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Default selling price. Overridden by Price Lists when assigned.', max_digits=15),
        ),
    ]
