# Generated by Django 6.0.2 on 2026-02-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_cost_price_item_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('FINISHED', 'Finished Product'), ('SERVICE', 'Service')], db_index=True, max_length=20),
        ),
    ]
