# Generated by Django 6.0.2 on 2026-03-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('FINISHED', 'Finished Product'), ('SERVICE', 'Service')], db_index=True, default='RAW', max_length=20),
        ),
    ]
