# Generated by Django 5.2.6 on 2026-03-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_item_selling_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='unit',
            name='category',
            field=models.CharField(choices=[('quantity', 'Quantity'), ('length', 'Length'), ('mass', 'Mass'), ('volume', 'Volume'), ('area', 'Area'), ('material', 'Material'), ('logistics', 'Logistics')], db_index=True, default='quantity', help_text='Measurement category — conversions are only allowed within the same category.', max_length=20),
        ),
    ]
