# Generated by Django 5.2.6 on 2026-05-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_unitconversion_conversion_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at', 'code']},
        ),
        migrations.AlterModelOptions(
            name='unitconversion',
            options={'ordering': ['-created_at']},
        ),
    ]
