-- Table: auth_permission (324 rows)
-- Paste this into Neon SQL Editor

INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES
  (1, 1, 'add_logentry', 'Can add log entry'),
  (2, 1, 'change_logentry', 'Can change log entry'),
  (3, 1, 'delete_logentry', 'Can delete log entry'),
  (4, 1, 'view_logentry', 'Can view log entry'),
  (5, 3, 'add_permission', 'Can add permission'),
  (6, 3, 'change_permission', 'Can change permission'),
  (7, 3, 'delete_permission', 'Can delete permission'),
  (8, 3, 'view_permission', 'Can view permission'),
  (9, 2, 'add_group', 'Can add group'),
  (10, 2, 'change_group', 'Can change group'),
  (11, 2, 'delete_group', 'Can delete group'),
  (12, 2, 'view_group', 'Can view group'),
  (13, 4, 'add_contenttype', 'Can add content type'),
  (14, 4, 'change_contenttype', 'Can change content type'),
  (15, 4, 'delete_contenttype', 'Can delete content type'),
  (16, 4, 'view_contenttype', 'Can view content type'),
  (17, 5, 'add_session', 'Can add session'),
  (18, 5, 'change_session', 'Can change session'),
  (19, 5, 'delete_session', 'Can delete session'),
  (20, 5, 'view_session', 'Can view session'),
  (21, 6, 'add_role', 'Can add role'),
  (22, 6, 'change_role', 'Can change role'),
  (23, 6, 'delete_role', 'Can delete role'),
  (24, 6, 'view_role', 'Can view role'),
  (25, 7, 'add_user', 'Can add user'),
  (26, 7, 'change_user', 'Can change user'),
  (27, 7, 'delete_user', 'Can delete user'),
  (28, 7, 'view_user', 'Can view user'),
  (29, 8, 'add_userrole', 'Can add user role'),
  (30, 8, 'change_userrole', 'Can change user role'),
  (31, 8, 'delete_userrole', 'Can delete user role'),
  (32, 8, 'view_userrole', 'Can view user role'),
  (33, 9, 'add_warehousepermission', 'Can add warehouse permission'),
  (34, 9, 'change_warehousepermission', 'Can change warehouse permission'),
  (35, 9, 'delete_warehousepermission', 'Can delete warehouse permission'),
  (36, 9, 'view_warehousepermission', 'Can view warehouse permission'),
  (37, 14, 'add_unit', 'Can add unit'),
  (38, 14, 'change_unit', 'Can change unit'),
  (39, 14, 'delete_unit', 'Can delete unit'),
  (40, 14, 'view_unit', 'Can view unit'),
  (41, 10, 'add_category', 'Can add category'),
  (42, 10, 'change_category', 'Can change category'),
  (43, 10, 'delete_category', 'Can delete category'),
  (44, 10, 'view_category', 'Can view category'),
  (45, 11, 'add_item', 'Can add item'),
  (46, 11, 'change_item', 'Can change item'),
  (47, 11, 'delete_item', 'Can delete item'),
  (48, 11, 'view_item', 'Can view item'),
  (49, 12, 'add_materialspec', 'Can add material spec'),
  (50, 12, 'change_materialspec', 'Can change material spec'),
  (51, 12, 'delete_materialspec', 'Can delete material spec'),
  (52, 12, 'view_materialspec', 'Can view material spec'),
  (53, 13, 'add_productspec', 'Can add product spec'),
  (54, 13, 'change_productspec', 'Can change product spec'),
  (55, 13, 'delete_productspec', 'Can delete product spec'),
  (56, 13, 'view_productspec', 'Can view product spec'),
  (57, 15, 'add_unitconversion', 'Can add unit conversion'),
  (58, 15, 'change_unitconversion', 'Can change unit conversion'),
  (59, 15, 'delete_unitconversion', 'Can delete unit conversion'),
  (60, 15, 'view_unitconversion', 'Can view unit conversion'),
  (61, 16, 'add_customer', 'Can add customer'),
  (62, 16, 'change_customer', 'Can change customer'),
  (63, 16, 'delete_customer', 'Can delete customer'),
  (64, 16, 'view_customer', 'Can view customer'),
  (65, 17, 'add_supplier', 'Can add supplier'),
  (66, 17, 'change_supplier', 'Can change supplier'),
  (67, 17, 'delete_supplier', 'Can delete supplier'),
  (68, 17, 'view_supplier', 'Can view supplier'),
  (69, 19, 'add_warehouse', 'Can add warehouse'),
  (70, 19, 'change_warehouse', 'Can change warehouse'),
  (71, 19, 'delete_warehouse', 'Can delete warehouse'),
  (72, 19, 'view_warehouse', 'Can view warehouse'),
  (73, 18, 'add_location', 'Can add location'),
  (74, 18, 'change_location', 'Can change location'),
  (75, 18, 'delete_location', 'Can delete location'),
  (76, 18, 'view_location', 'Can view location'),
  (77, 20, 'add_damagedreport', 'Can add damaged report'),
  (78, 20, 'change_damagedreport', 'Can change damaged report'),
  (79, 20, 'delete_damagedreport', 'Can delete damaged report'),
  (80, 20, 'view_damagedreport', 'Can view damaged report'),
  (81, 21, 'add_damagedreportline', 'Can add damaged report line'),
  (82, 21, 'change_damagedreportline', 'Can change damaged report line'),
  (83, 21, 'delete_damagedreportline', 'Can delete damaged report line'),
  (84, 21, 'view_damagedreportline', 'Can view damaged report line'),
  (85, 22, 'add_stockadjustment', 'Can add stock adjustment'),
  (86, 22, 'change_stockadjustment', 'Can change stock adjustment'),
  (87, 22, 'delete_stockadjustment', 'Can delete stock adjustment'),
  (88, 22, 'view_stockadjustment', 'Can view stock adjustment'),
  (89, 23, 'add_stockadjustmentline', 'Can add stock adjustment line'),
  (90, 23, 'change_stockadjustmentline', 'Can change stock adjustment line'),
  (91, 23, 'delete_stockadjustmentline', 'Can delete stock adjustment line'),
  (92, 23, 'view_stockadjustmentline', 'Can view stock adjustment line'),
  (93, 26, 'add_stockreservation', 'Can add stock reservation'),
  (94, 26, 'change_stockreservation', 'Can change stock reservation'),
  (95, 26, 'delete_stockreservation', 'Can delete stock reservation'),
  (96, 26, 'view_stockreservation', 'Can view stock reservation'),
  (97, 27, 'add_stocktransfer', 'Can add stock transfer'),
  (98, 27, 'change_stocktransfer', 'Can change stock transfer'),
  (99, 27, 'delete_stocktransfer', 'Can delete stock transfer'),
  (100, 27, 'view_stocktransfer', 'Can view stock transfer')
ON CONFLICT DO NOTHING;

INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES
  (101, 28, 'add_stocktransferline', 'Can add stock transfer line'),
  (102, 28, 'change_stocktransferline', 'Can change stock transfer line'),
  (103, 28, 'delete_stocktransferline', 'Can delete stock transfer line'),
  (104, 28, 'view_stocktransferline', 'Can view stock transfer line'),
  (105, 24, 'add_stockbalance', 'Can add stock balance'),
  (106, 24, 'change_stockbalance', 'Can change stock balance'),
  (107, 24, 'delete_stockbalance', 'Can delete stock balance'),
  (108, 24, 'view_stockbalance', 'Can view stock balance'),
  (109, 25, 'add_stockmove', 'Can add stock move'),
  (110, 25, 'change_stockmove', 'Can change stock move'),
  (111, 25, 'delete_stockmove', 'Can delete stock move'),
  (112, 25, 'view_stockmove', 'Can view stock move'),
  (113, 29, 'add_goodsreceipt', 'Can add goods receipt'),
  (114, 29, 'change_goodsreceipt', 'Can change goods receipt'),
  (115, 29, 'delete_goodsreceipt', 'Can delete goods receipt'),
  (116, 29, 'view_goodsreceipt', 'Can view goods receipt'),
  (117, 30, 'add_goodsreceiptline', 'Can add goods receipt line'),
  (118, 30, 'change_goodsreceiptline', 'Can change goods receipt line'),
  (119, 30, 'delete_goodsreceiptline', 'Can delete goods receipt line'),
  (120, 30, 'view_goodsreceiptline', 'Can view goods receipt line'),
  (121, 31, 'add_purchaseorder', 'Can add purchase order'),
  (122, 31, 'change_purchaseorder', 'Can change purchase order'),
  (123, 31, 'delete_purchaseorder', 'Can delete purchase order'),
  (124, 31, 'view_purchaseorder', 'Can view purchase order'),
  (125, 32, 'add_purchaseorderline', 'Can add purchase order line'),
  (126, 32, 'change_purchaseorderline', 'Can change purchase order line'),
  (127, 32, 'delete_purchaseorderline', 'Can delete purchase order line'),
  (128, 32, 'view_purchaseorderline', 'Can view purchase order line'),
  (129, 34, 'add_deliverynote', 'Can add delivery note'),
  (130, 34, 'change_deliverynote', 'Can change delivery note'),
  (131, 34, 'delete_deliverynote', 'Can delete delivery note'),
  (132, 34, 'view_deliverynote', 'Can view delivery note'),
  (133, 33, 'add_deliveryline', 'Can add delivery line'),
  (134, 33, 'change_deliveryline', 'Can change delivery line'),
  (135, 33, 'delete_deliveryline', 'Can delete delivery line'),
  (136, 33, 'view_deliveryline', 'Can view delivery line'),
  (137, 35, 'add_salesorder', 'Can add sales order'),
  (138, 35, 'change_salesorder', 'Can change sales order'),
  (139, 35, 'delete_salesorder', 'Can delete sales order'),
  (140, 35, 'view_salesorder', 'Can view sales order'),
  (141, 36, 'add_salesorderline', 'Can add sales order line'),
  (142, 36, 'change_salesorderline', 'Can change sales order line'),
  (143, 36, 'delete_salesorderline', 'Can delete sales order line'),
  (144, 36, 'view_salesorderline', 'Can view sales order line'),
  (145, 37, 'add_qrcodetag', 'Can add qr code tag'),
  (146, 37, 'change_qrcodetag', 'Can change qr code tag'),
  (147, 37, 'delete_qrcodetag', 'Can delete qr code tag'),
  (148, 37, 'view_qrcodetag', 'Can view qr code tag'),
  (149, 38, 'add_scanevent', 'Can add scan event'),
  (150, 38, 'change_scanevent', 'Can change scan event'),
  (151, 38, 'delete_scanevent', 'Can delete scan event'),
  (152, 38, 'view_scanevent', 'Can view scan event'),
  (153, 39, 'add_auditlog', 'Can add audit log'),
  (154, 39, 'change_auditlog', 'Can change audit log'),
  (155, 39, 'delete_auditlog', 'Can delete audit log'),
  (156, 39, 'view_auditlog', 'Can view audit log'),
  (157, 40, 'add_discountrule', 'Can add discount rule'),
  (158, 40, 'change_discountrule', 'Can change discount rule'),
  (159, 40, 'delete_discountrule', 'Can delete discount rule'),
  (160, 40, 'view_discountrule', 'Can view discount rule'),
  (161, 41, 'add_pricelist', 'Can add price list'),
  (162, 41, 'change_pricelist', 'Can change price list'),
  (163, 41, 'delete_pricelist', 'Can delete price list'),
  (164, 41, 'view_pricelist', 'Can view price list'),
  (165, 42, 'add_pricelistitem', 'Can add price list item'),
  (166, 42, 'change_pricelistitem', 'Can change price list item'),
  (167, 42, 'delete_pricelistitem', 'Can delete price list item'),
  (168, 42, 'view_pricelistitem', 'Can view price list item'),
  (169, 44, 'add_pospayment', 'Can add pos payment'),
  (170, 44, 'change_pospayment', 'Can change pos payment'),
  (171, 44, 'delete_pospayment', 'Can delete pos payment'),
  (172, 44, 'view_pospayment', 'Can view pos payment'),
  (173, 48, 'add_possale', 'Can add pos sale'),
  (174, 48, 'change_possale', 'Can change pos sale'),
  (175, 48, 'delete_possale', 'Can delete pos sale'),
  (176, 48, 'view_possale', 'Can view pos sale'),
  (177, 49, 'add_possaleline', 'Can add pos sale line'),
  (178, 49, 'change_possaleline', 'Can change pos sale line'),
  (179, 49, 'delete_possaleline', 'Can delete pos sale line'),
  (180, 49, 'view_possaleline', 'Can view pos sale line'),
  (181, 50, 'add_posshift', 'Can add pos shift'),
  (182, 50, 'change_posshift', 'Can change pos shift'),
  (183, 50, 'delete_posshift', 'Can delete pos shift'),
  (184, 50, 'view_posshift', 'Can view pos shift'),
  (185, 43, 'add_cashentry', 'Can add cash entry'),
  (186, 43, 'change_cashentry', 'Can change cash entry'),
  (187, 43, 'delete_cashentry', 'Can delete cash entry'),
  (188, 43, 'view_cashentry', 'Can view cash entry'),
  (189, 45, 'add_posrefund', 'Can add pos refund'),
  (190, 45, 'change_posrefund', 'Can change pos refund'),
  (191, 45, 'delete_posrefund', 'Can delete pos refund'),
  (192, 45, 'view_posrefund', 'Can view pos refund'),
  (193, 46, 'add_posrefundline', 'Can add pos refund line'),
  (194, 46, 'change_posrefundline', 'Can change pos refund line'),
  (195, 46, 'delete_posrefundline', 'Can delete pos refund line'),
  (196, 46, 'view_posrefundline', 'Can view pos refund line'),
  (197, 47, 'add_posregister', 'Can add pos register'),
  (198, 47, 'change_posregister', 'Can change pos register'),
  (199, 47, 'delete_posregister', 'Can delete pos register'),
  (200, 47, 'view_posregister', 'Can view pos register')
ON CONFLICT DO NOTHING;

INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES
  (201, 51, 'add_businessprofile', 'Can add Business Profile'),
  (202, 51, 'change_businessprofile', 'Can change Business Profile'),
  (203, 51, 'delete_businessprofile', 'Can delete Business Profile'),
  (204, 51, 'view_businessprofile', 'Can view Business Profile'),
  (205, 53, 'add_expensecategory', 'Can add expense category'),
  (206, 53, 'change_expensecategory', 'Can change expense category'),
  (207, 53, 'delete_expensecategory', 'Can delete expense category'),
  (208, 53, 'view_expensecategory', 'Can view expense category'),
  (209, 56, 'add_saleschannel', 'Can add sales channel'),
  (210, 56, 'change_saleschannel', 'Can change sales channel'),
  (211, 56, 'delete_saleschannel', 'Can delete sales channel'),
  (212, 56, 'view_saleschannel', 'Can view sales channel'),
  (213, 57, 'add_supplycategory', 'Can add supply category'),
  (214, 57, 'change_supplycategory', 'Can change supply category'),
  (215, 57, 'delete_supplycategory', 'Can delete supply category'),
  (216, 57, 'view_supplycategory', 'Can view supply category'),
  (217, 52, 'add_expense', 'Can add expense'),
  (218, 52, 'change_expense', 'Can change expense'),
  (219, 52, 'delete_expense', 'Can delete expense'),
  (220, 52, 'view_expense', 'Can view expense'),
  (221, 54, 'add_invoice', 'Can add invoice'),
  (222, 54, 'change_invoice', 'Can change invoice'),
  (223, 54, 'delete_invoice', 'Can delete invoice'),
  (224, 54, 'view_invoice', 'Can view invoice'),
  (225, 55, 'add_invoiceline', 'Can add invoice line'),
  (226, 55, 'change_invoiceline', 'Can change invoice line'),
  (227, 55, 'delete_invoiceline', 'Can delete invoice line'),
  (228, 55, 'view_invoiceline', 'Can view invoice line'),
  (229, 58, 'add_supplyitem', 'Can add supply item'),
  (230, 58, 'change_supplyitem', 'Can change supply item'),
  (231, 58, 'delete_supplyitem', 'Can delete supply item'),
  (232, 58, 'view_supplyitem', 'Can view supply item'),
  (233, 59, 'add_supplymovement', 'Can add supply movement'),
  (234, 59, 'change_supplymovement', 'Can change supply movement'),
  (235, 59, 'delete_supplymovement', 'Can delete supply movement'),
  (236, 59, 'view_supplymovement', 'Can view supply movement'),
  (237, 60, 'add_targetgoal', 'Can add target goal'),
  (238, 60, 'change_targetgoal', 'Can change target goal'),
  (239, 60, 'delete_targetgoal', 'Can delete target goal'),
  (240, 60, 'view_targetgoal', 'Can view target goal'),
  (241, 61, 'add_invoicepayment', 'Can add invoice payment'),
  (242, 61, 'change_invoicepayment', 'Can change invoice payment'),
  (243, 61, 'delete_invoicepayment', 'Can delete invoice payment'),
  (244, 61, 'view_invoicepayment', 'Can view invoice payment'),
  (245, 62, 'add_purchasereturn', 'Can add purchase return'),
  (246, 62, 'change_purchasereturn', 'Can change purchase return'),
  (247, 62, 'delete_purchasereturn', 'Can delete purchase return'),
  (248, 62, 'view_purchasereturn', 'Can view purchase return'),
  (249, 63, 'add_purchasereturnline', 'Can add purchase return line'),
  (250, 63, 'change_purchasereturnline', 'Can change purchase return line'),
  (251, 63, 'delete_purchasereturnline', 'Can delete purchase return line'),
  (252, 63, 'view_purchasereturnline', 'Can view purchase return line'),
  (253, 64, 'add_salesreturn', 'Can add sales return'),
  (254, 64, 'change_salesreturn', 'Can change sales return'),
  (255, 64, 'delete_salesreturn', 'Can delete sales return'),
  (256, 64, 'view_salesreturn', 'Can view sales return'),
  (257, 65, 'add_salesreturnline', 'Can add sales return line'),
  (258, 65, 'change_salesreturnline', 'Can change sales return line'),
  (259, 65, 'delete_salesreturnline', 'Can delete sales return line'),
  (260, 65, 'view_salesreturnline', 'Can view sales return line'),
  (261, 66, 'add_goodsreceiptattachment', 'Can add goods receipt attachment'),
  (262, 66, 'change_goodsreceiptattachment', 'Can change goods receipt attachment'),
  (263, 66, 'delete_goodsreceiptattachment', 'Can delete goods receipt attachment'),
  (264, 66, 'view_goodsreceiptattachment', 'Can view goods receipt attachment'),
  (265, 67, 'add_salesorderpricelistline', 'Can add sales order price list line'),
  (266, 67, 'change_salesorderpricelistline', 'Can change sales order price list line'),
  (267, 67, 'delete_salesorderpricelistline', 'Can delete sales order price list line'),
  (268, 67, 'view_salesorderpricelistline', 'Can view sales order price list line'),
  (269, 68, 'add_customerpricecatalog', 'Can add customer price catalog'),
  (270, 68, 'change_customerpricecatalog', 'Can change customer price catalog'),
  (271, 68, 'delete_customerpricecatalog', 'Can delete customer price catalog'),
  (272, 68, 'view_customerpricecatalog', 'Can view customer price catalog'),
  (273, 69, 'add_customerpricecatalogitem', 'Can add customer price catalog item'),
  (274, 69, 'change_customerpricecatalogitem', 'Can change customer price catalog item'),
  (275, 69, 'delete_customerpricecatalogitem', 'Can delete customer price catalog item'),
  (276, 69, 'view_customerpricecatalogitem', 'Can view customer price catalog item'),
  (277, 70, 'add_inventorytosupplytransfer', 'Can add inventory to supply transfer'),
  (278, 70, 'change_inventorytosupplytransfer', 'Can change inventory to supply transfer'),
  (279, 70, 'delete_inventorytosupplytransfer', 'Can delete inventory to supply transfer'),
  (280, 70, 'view_inventorytosupplytransfer', 'Can view inventory to supply transfer'),
  (281, 71, 'add_inventorytosupplytransferline', 'Can add inventory to supply transfer line'),
  (282, 71, 'change_inventorytosupplytransferline', 'Can change inventory to supply transfer line'),
  (283, 71, 'delete_inventorytosupplytransferline', 'Can delete inventory to supply transfer line'),
  (284, 71, 'view_inventorytosupplytransferline', 'Can view inventory to supply transfer line'),
  (285, 72, 'add_salespickup', 'Can add sales pickup'),
  (286, 72, 'change_salespickup', 'Can change sales pickup'),
  (287, 72, 'delete_salespickup', 'Can delete sales pickup'),
  (288, 72, 'view_salespickup', 'Can view sales pickup'),
  (289, 73, 'add_salespickupline', 'Can add sales pickup line'),
  (290, 73, 'change_salespickupline', 'Can change sales pickup line'),
  (291, 73, 'delete_salespickupline', 'Can delete sales pickup line'),
  (292, 73, 'view_salespickupline', 'Can view sales pickup line'),
  (293, 74, 'add_customerservice', 'Can add Customer Service'),
  (294, 74, 'change_customerservice', 'Can change Customer Service'),
  (295, 74, 'delete_customerservice', 'Can delete Customer Service'),
  (296, 74, 'view_customerservice', 'Can view Customer Service'),
  (297, 75, 'add_serviceline', 'Can add service line'),
  (298, 75, 'change_serviceline', 'Can change service line'),
  (299, 75, 'delete_serviceline', 'Can delete service line'),
  (300, 75, 'view_serviceline', 'Can view service line')
ON CONFLICT DO NOTHING;

INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES
  (301, 76, 'add_serviceothermaterial', 'Can add service other material'),
  (302, 76, 'change_serviceothermaterial', 'Can change service other material'),
  (303, 76, 'delete_serviceothermaterial', 'Can delete service other material'),
  (304, 76, 'view_serviceothermaterial', 'Can view service other material'),
  (305, 78, 'add_cashflowtransaction', 'Can add cash flow transaction'),
  (306, 78, 'change_cashflowtransaction', 'Can change cash flow transaction'),
  (307, 78, 'delete_cashflowtransaction', 'Can delete cash flow transaction'),
  (308, 78, 'view_cashflowtransaction', 'Can view cash flow transaction'),
  (309, 77, 'add_cashflowlog', 'Can add cash flow log'),
  (310, 77, 'change_cashflowlog', 'Can change cash flow log'),
  (311, 77, 'delete_cashflowlog', 'Can delete cash flow log'),
  (312, 77, 'view_cashflowlog', 'Can view cash flow log'),
  (313, 79, 'add_servicebundle', 'Can add service bundle'),
  (314, 79, 'change_servicebundle', 'Can change service bundle'),
  (315, 79, 'delete_servicebundle', 'Can delete service bundle'),
  (316, 79, 'view_servicebundle', 'Can view service bundle'),
  (317, 80, 'add_possalebundleline', 'Can add pos sale bundle line'),
  (318, 80, 'change_possalebundleline', 'Can change pos sale bundle line'),
  (319, 80, 'delete_possalebundleline', 'Can delete pos sale bundle line'),
  (320, 80, 'view_possalebundleline', 'Can view pos sale bundle line'),
  (321, 81, 'add_suppliercatalogentry', 'Can add Supplier Catalog Entry'),
  (322, 81, 'change_suppliercatalogentry', 'Can change Supplier Catalog Entry'),
  (323, 81, 'delete_suppliercatalogentry', 'Can delete Supplier Catalog Entry'),
  (324, 81, 'view_suppliercatalogentry', 'Can view Supplier Catalog Entry')
ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('auth_permission', 'id'), COALESCE((SELECT MAX(id) FROM "auth_permission"), 1));
