# Generated by Django 6.0.2 on 2026-02-12 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('printed', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_tags', to='catalog.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_tags', to='warehouses.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('RECEIVE', 'Receive'), ('MOVE', 'Move'), ('PICK', 'Pick'), ('COUNT', 'Count'), ('INFO', 'Info')], max_length=20)),
                ('qty', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='warehouses.location')),
                ('qr_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='qr.qrcodetag')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
