# Generated by Django 5.2.6 on 2026-03-31 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_unitconversion_conversion_price'),
        ('partners', '0001_initial'),
        ('procurement', '0003_goodsreceiptattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='Typical delivery lead time in days.', null=True)),
                ('last_po_date', models.DateField(blank=True, help_text='Date of the most recent PO this price was sourced from.', null=True)),
                ('last_po_number', models.CharField(blank=True, default='', help_text='Reference PO document number.', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_entries', to='catalog.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entries', to='partners.supplier')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit')),
            ],
            options={
                'verbose_name': 'Supplier Catalog Entry',
                'verbose_name_plural': 'Supplier Catalog Entries',
                'ordering': ['item__code', 'unit_price'],
                'unique_together': {('supplier', 'item', 'unit')},
            },
        ),
    ]
