# Generated by Django 6.0.2 on 2026-03-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_goodsreceiptattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='delivery_charges',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Optional delivery/freight charges. Allocated across items and included in COGS.', max_digits=15),
        ),
    ]
