# Generated by Django 6.0.2 on 2026-04-01 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_add_delivery_charges_to_goodsreceipt'),
        ('procurement', '0004_suppliercatalogentry'),
    ]

    operations = [
    ]
