# Generated by Django 6.0.2 on 2026-04-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_merge_20260401_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='delivery_charges',
        ),
    ]
