# Generated by Django 5.2.6 on 2026-04-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_remove_goodsreceipt_delivery_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Delivery/freight charge to be distributed across line items in cost calculation.', max_digits=15),
        ),
    ]
