# Generated by Django 5.2.6 on 2026-08-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_add_delivery_charge_to_goodsreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCatalogSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_resync_at', models.DateTimeField(blank=True, null=True)),
                ('last_catalog_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Supplier Catalog Sync State',
                'verbose_name_plural': 'Supplier Catalog Sync State',
            },
        ),
    ]
