# Generated by Django 5.2.6 on 2026-02-20 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expense_business_address_expense_item_description_and_more'),
        ('sales', '0002_salesorder_currency_salesorder_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], db_index=True, default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='receipt_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='core.saleschannel'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage for this line', max_digits=5),
        ),
    ]
