# Generated by Django 6.0.2 on 2026-03-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_payment_status_salesorder_receipt_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderline',
            name='discount_pct',
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Percentage (%)'), ('AMOUNT', 'Fixed Amount')], default='PERCENT', max_length=10),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='discount_value',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Discount amount or percentage depending on discount_type', max_digits=15),
        ),
    ]
