# Generated by Django 5.2.6 on 2026-03-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('sales', '0004_remove_salesorderline_discount_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderPriceListLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_multiplier', models.DecimalField(decimal_places=4, default=1, help_text='Multiply every PriceListItem qty by this factor (usually 1).', max_digits=15)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage (%)'), ('AMOUNT', 'Fixed Amount')], default='PERCENT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=4, default=0, help_text='Bundle-level discount applied on top of individual item prices.', max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='so_lines', to='pricing.pricelist')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_lines', to='sales.salesorder')),
            ],
        ),
    ]
