# Generated by Django 5.2.6 on 2026-03-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_salesorder_pricelistline'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryline',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
