# Generated by Django 5.2.6 on 2026-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salespickup_salespickupline'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='partial_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Amount already paid by the customer when payment status is Partially Paid.', max_digits=15, null=True),
        ),
    ]
