# Generated by Django 5.2.6 on 2026-05-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_add_partial_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery/shipping fee charged to the customer.', max_digits=15),
        ),
    ]
