# Generated by Django 5.2.6 on 2026-05-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_add_delivery_charge_to_salesorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-order_date', '-id']},
        ),
    ]
