# Generated by Django 5.2.6 on 2026-07-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_customerpricecatalog_effective_dates'),
        ('sales', '0010_alter_salesorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryline',
            name='sales_order_line',
            field=models.ForeignKey(blank=True, help_text='The specific SO line this delivery line fulfilled, set at posting time — lets cancellation reverse qty_delivered on exactly that line, even when the SO has more than one line for the same item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_lines', to='sales.salesorderline'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_rule',
            field=models.ForeignKey(blank=True, help_text='Optional promotional discount applied to this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='pricing.discountrule'),
        ),
        migrations.AddField(
            model_name='salespickupline',
            name='sales_order_line',
            field=models.ForeignKey(blank=True, help_text='The specific SO line this pickup line fulfilled, set at posting time — lets cancellation reverse qty_delivered on exactly that line, even when the SO has more than one line for the same item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_lines', to='sales.salesorderline'),
        ),
    ]
